packages:
  - 'factory'
  - 'factory/athena-api'
  - 'factory/athena-dashboard-ui'
  - 'dock'
  - 'sites/*'
  - 'sites-external/*'

onlyBuiltDependencies:
  - esbuild
  - lightningcss
  - core-js
  - canvas
