import React from 'react';
import { HashRouter as Router, Routes, Route } from 'react-router-dom';
import PageRenderer from './components/PageRenderer';
import Header from './components/Header';
import Footer from './components/Footer';
import Sitemap from './components/Sitemap';

function App() {
  const headerData = {
      title: "FPC Gent", logo: "https://www.fpcnv.be/wp-content/themes/fpc/images/logo_share.jpg", 
      nav: /* @NAV_ITEMS@ */ [ { "label": "Home", "href": "#/" }, { "label": "Over ons", "href": "#/over-ons" }, { "label": "Behandelen en beveiligen", "href": "#/behandelen-en-beveiligen" }, { "label": "Jobs", "href": "#/jobs" }, { "label": "Re integratie", "href": "#/re-integratie" }, { "label": "Events", "href": "#/events" }, { "label": "Contact", "href": "#/contact" }, { "label": "Covid 19 vaccinatiegraad van meer dan 95", "href": "#/covid-19-vaccinatiegraad-van-meer-dan-95" }, { "label": "Archief", "href": "#/sitemap" }
]
  };

  return (
    <Router>
        <div className="min-h-screen flex flex-col bg-white">
            <Header data={headerData} />
            
            <main className="flex-grow pt-28">
                <Routes>
                    <Route path="/covid-19-vaccinatiegraad-van-meer-dan-95" element={<PageRenderer file="covid-19-vaccinatiegraad-van-meer-dan-95.json" />} />
                    <Route path="/wij-dragen-zorg-voor-een-unieke-doelgroep-kom-en-neem-een-unieke-kijk-achter-de-schermen" element={<PageRenderer file="wij-dragen-zorg-voor-een-unieke-doelgroep-kom-en-neem-een-unieke-kijk-achter-de-schermen.json" />} />
                    <Route path="/ontdek-tijdens-de-open-geestdagen-wat-er-achter-onze-deuren-gebeurt" element={<PageRenderer file="ontdek-tijdens-de-open-geestdagen-wat-er-achter-onze-deuren-gebeurt.json" />} />
                    <Route path="/we-zijn-trots-op-wat-we-doen" element={<PageRenderer file="we-zijn-trots-op-wat-we-doen.json" />} />
                    <Route path="/inspectiebezoek-fpc-antwerpen-en-fpc-gent-een-positief-rapport-met-groeikansen-voor-organisatie-en-sector" element={<PageRenderer file="inspectiebezoek-fpc-antwerpen-en-fpc-gent-een-positief-rapport-met-groeikansen-voor-organisatie-en-sector.json" />} />
                    <Route path="/bezoekdag-voor-familie-en-naastbetrokkenen-2" element={<PageRenderer file="bezoekdag-voor-familie-en-naastbetrokkenen-2.json" />} />
                    <Route path="/dag-van-de-zorg-zondag-15-mei-2022" element={<PageRenderer file="dag-van-de-zorg-zondag-15-mei-2022.json" />} />
                    <Route path="/jerusalema-dance-challenge-fpc-gent" element={<PageRenderer file="jerusalema-dance-challenge-fpc-gent.json" />} />
                    <Route path="/open-deuren-in-fpc-antwerpen-en-fpc-gent" element={<PageRenderer file="open-deuren-in-fpc-antwerpen-en-fpc-gent.json" />} />
                    <Route path="/bezoekdag-voor-familie-en-naastbetrokkenen" element={<PageRenderer file="bezoekdag-voor-familie-en-naastbetrokkenen.json" />} />
                    <Route path="/integrin-duurzaamheid-en-sociale-integratie-gaan-hand-in-hand" element={<PageRenderer file="integrin-duurzaamheid-en-sociale-integratie-gaan-hand-in-hand.json" />} />
                    <Route path="/buurtdag-fpc-antwerpen" element={<PageRenderer file="buurtdag-fpc-antwerpen.json" />} />
                    <Route path="/officiele-erkenning-voor-kwaliteitsbeleid-binnen-de-zorg" element={<PageRenderer file="officiele-erkenning-voor-kwaliteitsbeleid-binnen-de-zorg.json" />} />
                    <Route path="/tevredenheidsonderzoek-familieleden-van-geinterneerden" element={<PageRenderer file="tevredenheidsonderzoek-familieleden-van-geinterneerden.json" />} />
                    <Route path="/fpc-antwerpen-en-fpc-gent-nemen-maatregelen-om-de-verspreiding-van-het-coronavirus-af-te-remmen" element={<PageRenderer file="fpc-antwerpen-en-fpc-gent-nemen-maatregelen-om-de-verspreiding-van-het-coronavirus-af-te-remmen.json" />} />
                    <Route path="/uitstroomresultaten-kennen-positieve-evolutie" element={<PageRenderer file="uitstroomresultaten-kennen-positieve-evolutie.json" />} />
                    <Route path="/gezamenlijke-inspanningen-en-innovatief-beleid-voor-de-behandeling-van-forensisch-psychiatrische-patienten-leiden-tot-goede-uitstroomresultaten" element={<PageRenderer file="gezamenlijke-inspanningen-en-innovatief-beleid-voor-de-behandeling-van-forensisch-psychiatrische-patienten-leiden-tot-goede-uitstroomresultaten.json" />} />
                    <Route path="/laagdrempelige-ombudsfunctie-garandeert-mee-kwaliteit-zorg" element={<PageRenderer file="laagdrempelige-ombudsfunctie-garandeert-mee-kwaliteit-zorg.json" />} />
                    <Route path="/de-patient-centraal-in-het-zorglandschap" element={<PageRenderer file="de-patient-centraal-in-het-zorglandschap.json" />} />
                    <Route path="/kwalitatieve-zorg-groene-handen" element={<PageRenderer file="kwalitatieve-zorg-groene-handen.json" />} />
                    <Route path="/preventief-werken-om-incidenten-voorkomen" element={<PageRenderer file="preventief-werken-om-incidenten-voorkomen.json" />} />
                    <Route path="/warmlopen-goede-doel-en-re-integratie" element={<PageRenderer file="warmlopen-goede-doel-en-re-integratie.json" />} />
                    <Route path="/betere-kansen-op-resocialisatie-zinvolle-dagbesteding" element={<PageRenderer file="betere-kansen-op-resocialisatie-zinvolle-dagbesteding.json" />} />
                    <Route path="/ondersteuningsfonds-menswaardig-leven-en-resocialisatie" element={<PageRenderer file="ondersteuningsfonds-menswaardig-leven-en-resocialisatie.json" />} />
                    <Route path="/zoeken-naar-evenwicht-behandelen-en-beheersen" element={<PageRenderer file="zoeken-naar-evenwicht-behandelen-en-beheersen.json" />} />
                    <Route path="/informatie-patienten-dunne-grens-sociaal-contact-en-zoeken-naar-aandacht" element={<PageRenderer file="informatie-patienten-dunne-grens-sociaal-contact-en-zoeken-naar-aandacht.json" />} />
                    <Route path="/buiten-naar-binnen-halen-sporten" element={<PageRenderer file="buiten-naar-binnen-halen-sporten.json" />} />
                    <Route path="/congres-zeer-intensieve-zorg-binnen-forensische-psychiatrie" element={<PageRenderer file="congres-zeer-intensieve-zorg-binnen-forensische-psychiatrie.json" />} />
                    <Route path="/uitstroom-fpc-gent" element={<PageRenderer file="uitstroom-fpc-gent.json" />} />
                    <Route path="/incidenten-en-stressvolle-gebeurtenissen-forensische-psychiatrie" element={<PageRenderer file="incidenten-en-stressvolle-gebeurtenissen-forensische-psychiatrie.json" />} />
                    <Route path="/humane-aanpak-respect-ieders-veiligheid" element={<PageRenderer file="humane-aanpak-respect-ieders-veiligheid.json" />} />
                    <Route path="/somatische-zorg-vergelijkbaar-gezondheidszorg-vrije-samenleving" element={<PageRenderer file="somatische-zorg-vergelijkbaar-gezondheidszorg-vrije-samenleving.json" />} />
                    <Route path="/destigmatisering-geinterneerden-mensen-beeld" element={<PageRenderer file="destigmatisering-geinterneerden-mensen-beeld.json" />} />
                    <Route path="/gevarieerd-team-optimale-begeleiding-patienten" element={<PageRenderer file="gevarieerd-team-optimale-begeleiding-patienten.json" />} />
                    <Route path="/vrijheidsbeperkende-maatregelen-straffen-beschermen" element={<PageRenderer file="vrijheidsbeperkende-maatregelen-straffen-beschermen.json" />} />
                    <Route path="/onderzoek-naar-onze-patientenpopulatie" element={<PageRenderer file="onderzoek-naar-onze-patientenpopulatie.json" />} />
                    <Route path="/bezoekdag-voor-familie-en-naasten-van-patienten" element={<PageRenderer file="bezoekdag-voor-familie-en-naasten-van-patienten.json" />} />
                    <Route path="/kleine-stapjes-met-een-grote-betekenis" element={<PageRenderer file="kleine-stapjes-met-een-grote-betekenis.json" />} />
                    <Route path="/stap-voor-stap-richting-richting-maatschappij" element={<PageRenderer file="stap-voor-stap-richting-richting-maatschappij.json" />} />
                    <Route path="/personen-met-psychosegevoeligheid-komen-op-adem-in-een-comfort-room" element={<PageRenderer file="personen-met-psychosegevoeligheid-komen-op-adem-in-een-comfort-room.json" />} />
                    <Route path="/somatische-pathologie" element={<PageRenderer file="somatische-pathologie.json" />} />
                    <Route path="/uitstroom-en-patientenpopulatie" element={<PageRenderer file="uitstroom-en-patientenpopulatie.json" />} />
                    <Route path="/psychomotorische-therapie-als-onderdeel-van-de-behandeling" element={<PageRenderer file="psychomotorische-therapie-als-onderdeel-van-de-behandeling.json" />} />
                    <Route path="/fpc-antwerpen-en-fpc-gent-versturen-van-privacygevoelige-informatie-op-een-veilige-manier" element={<PageRenderer file="fpc-antwerpen-en-fpc-gent-versturen-van-privacygevoelige-informatie-op-een-veilige-manier.json" />} />
                    <Route path="/het-belangrijk-is-dat-patienten-zich-niet-enkel-dader-maar-vooral-ook-mens-voelen" element={<PageRenderer file="het-belangrijk-is-dat-patienten-zich-niet-enkel-dader-maar-vooral-ook-mens-voelen.json" />} />
                    <Route path="/familiedag-mercatordok-een-ongedwongen-moment-van-samenzijn" element={<PageRenderer file="familiedag-mercatordok-een-ongedwongen-moment-van-samenzijn.json" />} />
                    <Route path="/verborgen-kunstenaars-in-de-spotlight" element={<PageRenderer file="verborgen-kunstenaars-in-de-spotlight.json" />} />
                    <Route path="/leren-om-de-de-kansen-op-re-integratie-en-zelfredzaamheid-te-maximaliseren" element={<PageRenderer file="leren-om-de-de-kansen-op-re-integratie-en-zelfredzaamheid-te-maximaliseren.json" />} />
                    <Route path="/het-profiel-van-de-patienten-in-fpc-antwerpen-en-fpc-gent" element={<PageRenderer file="het-profiel-van-de-patienten-in-fpc-antwerpen-en-fpc-gent.json" />} />
                    <Route path="/telkens-wordt-de-deur-voor-je-neus-dichtgegooid" element={<PageRenderer file="telkens-wordt-de-deur-voor-je-neus-dichtgegooid.json" />} />
                    <Route path="/ontvluchtingen-en-onttrekkingen-van-patienten-uit-de-vlaamse-forensisch-psychiatrische-centra" element={<PageRenderer file="ontvluchtingen-en-onttrekkingen-van-patienten-uit-de-vlaamse-forensisch-psychiatrische-centra.json" />} />
                    <Route path="/fpc-antwerpen-werkt-samen-met-de-buurtgemeenten-aan-het-milieu" element={<PageRenderer file="fpc-antwerpen-werkt-samen-met-de-buurtgemeenten-aan-het-milieu.json" />} />
                    <Route path="/congres-gestoord-of-ongestoord-seksualiteit-in-de-residentiele-forensische-zorg" element={<PageRenderer file="congres-gestoord-of-ongestoord-seksualiteit-in-de-residentiele-forensische-zorg.json" />} />
                    <Route path="/netwerkdag-internering-voor-hulpverleners-binnen-zorg-en-justitie" element={<PageRenderer file="netwerkdag-internering-voor-hulpverleners-binnen-zorg-en-justitie.json" />} />
                    <Route path="/mens-sana-in-corpore-sano" element={<PageRenderer file="mens-sana-in-corpore-sano.json" />} />
                    <Route path="/een-behandelplan-op-maat-van-de-patient-innovatie-in-zorg" element={<PageRenderer file="een-behandelplan-op-maat-van-de-patient-innovatie-in-zorg.json" />} />
                    <Route path="/mvc-team-spirit-een-uniek-project" element={<PageRenderer file="mvc-team-spirit-een-uniek-project.json" />} />
                    <Route path="/opinie-geinterneerden-breng-zorg-doorstroom-en-veiligheid-in-balans" element={<PageRenderer file="opinie-geinterneerden-breng-zorg-doorstroom-en-veiligheid-in-balans.json" />} />
                    <Route path="/drama-veelzijdige-ervaringsgerichte-therapie" element={<PageRenderer file="drama-veelzijdige-ervaringsgerichte-therapie.json" />} />
                    <Route path="/kunst-dat-is-twee-keer-kijken" element={<PageRenderer file="kunst-dat-is-twee-keer-kijken.json" />} />
                    <Route path="/samen-op-weg-de-betrokkenheid-van-familie-en-naasten-bij-het-traject-van-patienten" element={<PageRenderer file="samen-op-weg-de-betrokkenheid-van-familie-en-naasten-bij-het-traject-van-patienten.json" />} />
                    <Route path="/een-nieuwe-beleving-de-autismebelevingscircuits-box-van-autisme-centraal" element={<PageRenderer file="een-nieuwe-beleving-de-autismebelevingscircuits-box-van-autisme-centraal.json" />} />
                    <Route path="/een-dag-van-trots" element={<PageRenderer file="een-dag-van-trots.json" />} />
                    <Route path="/een-brug-tussen-binnen-en-buiten-twee-werelden-vinden-elkaar-tijdens-de-eerste-editie-van-parle-fpc" element={<PageRenderer file="een-brug-tussen-binnen-en-buiten-twee-werelden-vinden-elkaar-tijdens-de-eerste-editie-van-parle-fpc.json" />} />
                    <Route path="/zorg-ook-voor-de-ziel-over-spiritualiteit-en-pastoraat-in-de-forensische-psychiatrie" element={<PageRenderer file="zorg-ook-voor-de-ziel-over-spiritualiteit-en-pastoraat-in-de-forensische-psychiatrie.json" />} />
                    <Route path="/van-stilte-naar-samenspel-muziektherapie-in-de-forensische-psychiatrie" element={<PageRenderer file="van-stilte-naar-samenspel-muziektherapie-in-de-forensische-psychiatrie.json" />} />
                    <Route path="/waar-zorg-en-complexiteit-samenkomen-de-zeer-intensieve-zorgafdeling-als-baken-voor-patienten-met-specifieke-zorgnoden" element={<PageRenderer file="waar-zorg-en-complexiteit-samenkomen-de-zeer-intensieve-zorgafdeling-als-baken-voor-patienten-met-specifieke-zorgnoden.json" />} />
                    <Route path="/de-kracht-van-schematherapie-in-persoonlijke-transformatie" element={<PageRenderer file="de-kracht-van-schematherapie-in-persoonlijke-transformatie.json" />} />
                    <Route path="/waar-geen-dag-hetzelfde-is-maar-elke-dag-telt" element={<PageRenderer file="waar-geen-dag-hetzelfde-is-maar-elke-dag-telt.json" />} />
                    <Route path="/onderwijs-als-hefboom-tot-herstel-centrum-voor-volwassenonderwijs-kisp-versterkt-kansen-van-patienten" element={<PageRenderer file="onderwijs-als-hefboom-tot-herstel-centrum-voor-volwassenonderwijs-kisp-versterkt-kansen-van-patienten.json" />} />
                    <Route path="/kunst-buiten-de-muren" element={<PageRenderer file="kunst-buiten-de-muren.json" />} />
                    <Route path="/droomuitstappen-geluk-brengen-maakt-gelukkig" element={<PageRenderer file="droomuitstappen-geluk-brengen-maakt-gelukkig.json" />} />
                    <Route path="/het-welzijn-van-onze-werknemers-is-ook-onze-zorg" element={<PageRenderer file="het-welzijn-van-onze-werknemers-is-ook-onze-zorg.json" />} />
                    <Route path="/tussen-voorwaarden-en-vrijheid" element={<PageRenderer file="tussen-voorwaarden-en-vrijheid.json" />} />
                    <Route path="/waar-samen-werken-aan-herstel-samenwerken-wordt" element={<PageRenderer file="waar-samen-werken-aan-herstel-samenwerken-wordt.json" />} />
                    <Route path="/oprichting-van-het-expertisecentrum-voor-de-forensische-hulpverlener" element={<PageRenderer file="oprichting-van-het-expertisecentrum-voor-de-forensische-hulpverlener.json" />} />
                    <Route path="/wat-als-therapie-niet-met-woorden-begint-beelden-als-brug-naar-contact" element={<PageRenderer file="wat-als-therapie-niet-met-woorden-begint-beelden-als-brug-naar-contact.json" />} />
                    <Route path="/de-moestuin-van-tolhuis" element={<PageRenderer file="de-moestuin-van-tolhuis.json" />} />
                    <Route path="/inclusie-en-beweging" element={<PageRenderer file="inclusie-en-beweging.json" />} />
                    <Route path="/samenwerking-met-aap-vzw-honden-die-zorgen-voor-verbinding-en-geluksmomenten" element={<PageRenderer file="samenwerking-met-aap-vzw-honden-die-zorgen-voor-verbinding-en-geluksmomenten.json" />} />
                    <Route path="/herbronning-binnen-de-forensisch-psychiatrische-zorg" element={<PageRenderer file="herbronning-binnen-de-forensisch-psychiatrische-zorg.json" />} />
                    <Route path="/evolutie-van-het-risico-op-herval-in-geweldsdelicten-bestaan-er-verschillende-trajecten" element={<PageRenderer file="evolutie-van-het-risico-op-herval-in-geweldsdelicten-bestaan-er-verschillende-trajecten.json" />} />
                    <Route path="/officiele-erkenning-voor-kwaliteitsbeleid-binnen-de-zorg-2" element={<PageRenderer file="officiele-erkenning-voor-kwaliteitsbeleid-binnen-de-zorg-2.json" />} />
                    <Route path="/hoofgeneesheer-fpc-gent-in-de-volksjury-achter-de-crime-scene" element={<PageRenderer file="hoofgeneesheer-fpc-gent-in-de-volksjury-achter-de-crime-scene.json" />} />
                    <Route path="/meer-dan-meubels-hoe-een-huiselijke-leefgroep-voor-meer-contact-en-welzijn-zorgt" element={<PageRenderer file="meer-dan-meubels-hoe-een-huiselijke-leefgroep-voor-meer-contact-en-welzijn-zorgt.json" />} />
                    <Route path="/" element={<PageRenderer file="home.json" />} />
                    <Route path="/re-integratie/doorstroom-en-uitstroom" element={<PageRenderer file="re-integratie_doorstroom-en-uitstroom.json" />} />
                    <Route path="/re-integratie/kennisdelen" element={<PageRenderer file="re-integratie_kennisdelen.json" />} />
                    <Route path="/jobs/sollicitatieprocedure" element={<PageRenderer file="jobs_sollicitatieprocedure.json" />} />
                    <Route path="/contact" element={<PageRenderer file="contact.json" />} />
                    <Route path="/forensische-psychiatrie" element={<PageRenderer file="forensische-psychiatrie.json" />} />
                    <Route path="/re-integratie" element={<PageRenderer file="re-integratie.json" />} />
                    <Route path="/jobs/spontaan-solliciteren" element={<PageRenderer file="jobs_spontaan-solliciteren.json" />} />
                    <Route path="/behandelcentra/aangemeld-wat-nu" element={<PageRenderer file="behandelcentra_aangemeld-wat-nu.json" />} />
                    <Route path="/re-integratie/samenwerking-ketenpartners" element={<PageRenderer file="re-integratie_samenwerking-ketenpartners.json" />} />
                    <Route path="/behandelcentra" element={<PageRenderer file="behandelcentra.json" />} />
                    <Route path="/forensische-psychiatrie/forensisch-psychiatrisch-centrum" element={<PageRenderer file="forensische-psychiatrie_forensisch-psychiatrisch-centrum.json" />} />
                    <Route path="/behandelen-en-beveiligen/zorg-op-maat" element={<PageRenderer file="behandelen-en-beveiligen_zorg-op-maat.json" />} />
                    <Route path="/behandelen-en-beveiligen" element={<PageRenderer file="behandelen-en-beveiligen.json" />} />
                    <Route path="/behandelen-en-beveiligen/behandeltraject" element={<PageRenderer file="behandelen-en-beveiligen_behandeltraject.json" />} />
                    <Route path="/jobs/aan-de-slag-in" element={<PageRenderer file="jobs_aan-de-slag-in.json" />} />
                    <Route path="/forensische-psychiatrie/internering" element={<PageRenderer file="forensische-psychiatrie_internering.json" />} />
                    <Route path="/disclaimer" element={<PageRenderer file="disclaimer.json" />} />
                    <Route path="/over-ons" element={<PageRenderer file="over-ons.json" />} />
                    <Route path="/over-ons/privacybeleid" element={<PageRenderer file="over-ons_privacybeleid.json" />} />
                    <Route path="/over-ons/website-disclaimer-en-cookiebeleid" element={<PageRenderer file="over-ons_website-disclaimer-en-cookiebeleid.json" />} />
                    <Route path="/jobs/collegas-getuigen" element={<PageRenderer file="jobs_collegas-getuigen.json" />} />
                    <Route path="/jobs/studenten-on-tour" element={<PageRenderer file="jobs_studenten-on-tour.json" />} />
                    <Route path="/jobs/stages" element={<PageRenderer file="jobs_stages.json" />} />
                    <Route path="/jobs/kiezen-voor-fpc-antwerpen-of-fpc-gent" element={<PageRenderer file="jobs_kiezen-voor-fpc-antwerpen-of-fpc-gent.json" />} />
                    <Route path="/behandelen-en-beveiligen/behandelingsconcept" element={<PageRenderer file="behandelen-en-beveiligen_behandelingsconcept.json" />} />
                    <Route path="/over-ons/veilig-versturen-van-privacygevoelige-informatie" element={<PageRenderer file="over-ons_veilig-versturen-van-privacygevoelige-informatie.json" />} />
                    <Route path="/nieuws-en-informatie" element={<PageRenderer file="nieuws-en-informatie.json" />} />
                    <Route path="/nieuws-en-informatie/pers" element={<PageRenderer file="nieuws-en-informatie_pers.json" />} />
                    <Route path="/over-ons/klokkenluiderskanaal" element={<PageRenderer file="over-ons_klokkenluiderskanaal.json" />} />
                    <Route path="/jobs" element={<PageRenderer file="jobs.json" />} />
                    <Route path="/behandelcentra/fpc-antwerpen" element={<PageRenderer file="behandelcentra_fpc-antwerpen.json" />} />
                    <Route path="/behandelcentra/fpc-gent" element={<PageRenderer file="behandelcentra_fpc-gent.json" />} />
                    <Route path="/over-ons/ombudsdienst" element={<PageRenderer file="over-ons_ombudsdienst.json" />} />
                    <Route path="/fpc-antwerpen-en-fpc-gent-behandeling-en-operationele-uitdagingen" element={<PageRenderer file="fpc-antwerpen-en-fpc-gent-behandeling-en-operationele-uitdagingen.json" />} />
                    <Route path="/de-interne-rechtspositieregeling-in-een-high-security-setting-welke-lessen-kunnen-geleerd-worden-uit-de-nederlandse-situatie" element={<PageRenderer file="de-interne-rechtspositieregeling-in-een-high-security-setting-welke-lessen-kunnen-geleerd-worden-uit-de-nederlandse-situatie.json" />} />
                    <Route path="/de-verbanden-tussen-identiteit-en-zowel-risico-als-beschermende-factoren-met-betrekking-tot-gewelddadige-recidive-bij-volwassen-forensische-patienten" element={<PageRenderer file="de-verbanden-tussen-identiteit-en-zowel-risico-als-beschermende-factoren-met-betrekking-tot-gewelddadige-recidive-bij-volwassen-forensische-patienten.json" />} />
                    <Route path="/een-8-jaar-durende-studie-naar-ontvluchtingen-en-onttrekkingen-uit-de-forensisch-psychiatrische-centra" element={<PageRenderer file="een-8-jaar-durende-studie-naar-ontvluchtingen-en-onttrekkingen-uit-de-forensisch-psychiatrische-centra.json" />} />
                    <Route path="/evolutie-van-risico-op-gewelddadige-recidive" element={<PageRenderer file="evolutie-van-risico-op-gewelddadige-recidive.json" />} />
                    <Route path="/uitmuntendheid-in-forensische-psychiatrie-internationaal-onderzoek-naar-kwaliteiten-en-correlaties" element={<PageRenderer file="uitmuntendheid-in-forensische-psychiatrie-internationaal-onderzoek-naar-kwaliteiten-en-correlaties.json" />} />
                    <Route path="/forensisch-psychiatrisch-centrum-gent-binnenstebuiten" element={<PageRenderer file="forensisch-psychiatrisch-centrum-gent-binnenstebuiten.json" />} />
                    <Route path="/fysieke-gezondheid-van-patienten" element={<PageRenderer file="fysieke-gezondheid-van-patienten.json" />} />
                    <Route path="/het-gebruik-van-vrijheidsbeperkende-maatregelen-in-een-hoog-beveiligde-setting-in-belgie-prevalentie-en-risicofactoren" element={<PageRenderer file="het-gebruik-van-vrijheidsbeperkende-maatregelen-in-een-hoog-beveiligde-setting-in-belgie-prevalentie-en-risicofactoren.json" />} />
                    <Route path="/het-profiel-van-high-security-geinterneerden" element={<PageRenderer file="het-profiel-van-high-security-geinterneerden.json" />} />
                    <Route path="/high-security-geinterneerden-wie-zijn-zij-waar-komen-ze-vandaan-waar-gaan-zij-niet-naartoe" element={<PageRenderer file="high-security-geinterneerden-wie-zijn-zij-waar-komen-ze-vandaan-waar-gaan-zij-niet-naartoe.json" />} />
                    <Route path="/patientenprofielen" element={<PageRenderer file="patientenprofielen.json" />} />
                    <Route path="/somatische-pathologie-bij-high-security-geinterneerden" element={<PageRenderer file="somatische-pathologie-bij-high-security-geinterneerden.json" />} />
                    <Route path="/uitstroom-en-uitstroompotentieel-van-de-opgenomen-patienten" element={<PageRenderer file="uitstroom-en-uitstroompotentieel-van-de-opgenomen-patienten.json" />} />
                    <Route path="/welzijn-tijdens-covid-19" element={<PageRenderer file="welzijn-tijdens-covid-19.json" />} />
                    <Route path="/zelfregulatie" element={<PageRenderer file="zelfregulatie.json" />} />
                    <Route path="/expertisecentrum/opleidingen" element={<PageRenderer file="expertisecentrum_opleidingen.json" />} />
                    <Route path="/expertisecentrum" element={<PageRenderer file="expertisecentrum.json" />} />
                    <Route path="/expertisecentrum/over-expertisecentrum-forensische-hulpverlener" element={<PageRenderer file="expertisecentrum_over-expertisecentrum-forensische-hulpverlener.json" />} />
                    <Route path="/over-ons/aandeelhouders-met-expertise" element={<PageRenderer file="over-ons_aandeelhouders-met-expertise.json" />} />
                    <Route path="/evolutie-van-het-risico-op-herval-in-geweldsdelicten-verschillende-trajecten" element={<PageRenderer file="evolutie-van-het-risico-op-herval-in-geweldsdelicten-verschillende-trajecten.json" />} />
                    <Route path="/expertisecentrum/praktijkgericht-onderzoek" element={<PageRenderer file="expertisecentrum_praktijkgericht-onderzoek.json" />} />
                    <Route path="/jobs/jobevents" element={<PageRenderer file="jobs_jobevents.json" />} />
                    <Route path="/jobs/job-landingspagina-verpleegkundige" element={<PageRenderer file="jobs_job-landingspagina-verpleegkundige.json" />} />
                    <Route path="/jobs/job-landingspagina-woon-en-leefgroepbegeleider" element={<PageRenderer file="jobs_job-landingspagina-woon-en-leefgroepbegeleider.json" />} />
                    <Route path="/jobs/job-landingspagina-sociotherapie" element={<PageRenderer file="jobs_job-landingspagina-sociotherapie.json" />} />
                    <Route path="/jobs/job-landingspagina-therapeutisch-assistent-groepsbegeleider" element={<PageRenderer file="jobs_job-landingspagina-therapeutisch-assistent-groepsbegeleider.json" />} />
                    <Route path="/forensische-psychiatrie/header-1" element={<PageRenderer file="forensische-psychiatrie_header-1.json" />} />
                    <Route path="/forensische-psychiatrie/forensisch-psychiatrisch-centrum/header-2" element={<PageRenderer file="forensische-psychiatrie_forensisch-psychiatrisch-centrum_header-2.json" />} />
                    <Route path="/forensische-psychiatrie/internering/fpc-blok7" element={<PageRenderer file="forensische-psychiatrie_internering_fpc-blok7.json" />} />
                    <Route path="/home/fpc-blok1" element={<PageRenderer file="home_fpc-blok1.json" />} />
                    <Route path="/home/fpc-blok2" element={<PageRenderer file="home_fpc-blok2.json" />} />
                    <Route path="/home/logo-fpc-antwerpen" element={<PageRenderer file="home_logo-fpc-antwerpen.json" />} />
                    <Route path="/jobs/kiezen-voor-fpc-antwerpen-of-fpc-gent/fpc-blok9" element={<PageRenderer file="jobs_kiezen-voor-fpc-antwerpen-of-fpc-gent_fpc-blok9.json" />} />
                    <Route path="/behandelen-en-beveiligen/behandelen-en-beveiligen-2" element={<PageRenderer file="behandelen-en-beveiligen_behandelen-en-beveiligen-2.json" />} />
                    <Route path="/re-integratie/samenwerking-ketenpartners/re-integratie-2" element={<PageRenderer file="re-integratie_samenwerking-ketenpartners_re-integratie-2.json" />} />
                    <Route path="/re-integratie/doorstroom-en-uitstroom/re-integratie_doorstroom-en-uitstroom" element={<PageRenderer file="re-integratie_doorstroom-en-uitstroom_re-integratie_doorstroom-en-uitstroom.json" />} />
                    <Route path="/re-integratie/samenwerking-ketenpartners/re-integratie_samenwerking-ketenpartners" element={<PageRenderer file="re-integratie_samenwerking-ketenpartners_re-integratie_samenwerking-ketenpartners.json" />} />
                    <Route path="/forensische-psychiatrie/internering/header-3" element={<PageRenderer file="forensische-psychiatrie_internering_header-3.json" />} />
                    <Route path="/jobs/jobs_sollicitatieprocedure" element={<PageRenderer file="jobs_jobs_sollicitatieprocedure.json" />} />
                    <Route path="/forensische-psychiatrie/link-img-1" element={<PageRenderer file="forensische-psychiatrie_link-img-1.json" />} />
                    <Route path="/behandelcentra/fpc-gent/fpc-blok3" element={<PageRenderer file="behandelcentra_fpc-gent_fpc-blok3.json" />} />
                    <Route path="/preventief-werken-om-incidenten-voorkomen/fpc-01" element={<PageRenderer file="preventief-werken-om-incidenten-voorkomen_fpc-01.json" />} />
                    <Route path="/ondersteuningsfonds-menswaardig-leven-en-resocialisatie/15216forensisch_psychiatrisch_centrum_antwerpen_vk_architects_and_engineers_denys_4_" element={<PageRenderer file="ondersteuningsfonds-menswaardig-leven-en-resocialisatie_15216forensisch_psychiatrisch_centrum_antwerpen_vk_architects_and_engineers_denys_4_.json" />} />
                    <Route path="/over-ons/over-ons_missie-en-visie" element={<PageRenderer file="over-ons_over-ons_missie-en-visie.json" />} />
                    <Route path="/home/fpc-gent-2" element={<PageRenderer file="home_fpc-gent-2.json" />} />
                    <Route path="/home/logo-fpc-antwerpen-square" element={<PageRenderer file="home_logo-fpc-antwerpen-square.json" />} />
                    <Route path="/home/fpcg_inkom" element={<PageRenderer file="home_fpcg_inkom.json" />} />
                    <Route path="/behandelcentra/fpc-gent/fpc-gebouw" element={<PageRenderer file="behandelcentra_fpc-gent_fpc-gebouw.json" />} />
                    <Route path="/behandelcentra/hoog-beveiligde-centra-2" element={<PageRenderer file="behandelcentra_hoog-beveiligde-centra-2.json" />} />
                    <Route path="/jobs/friendship-together-bonding-unity-youth-culture-concept" element={<PageRenderer file="jobs_friendship-together-bonding-unity-youth-culture-concept.json" />} />
                    <Route path="/nieuws-en-informatie/nieuwsmodule_destigmatisering-van-gei%cc%88nterneerden-mensen-in-beeld" element={<PageRenderer file="nieuws-en-informatie_nieuwsmodule_destigmatisering-van-gei%cc%88nterneerden-mensen-in-beeld.json" />} />
                    <Route path="/behandelen-en-beveiligen/zorg-op-maat/behandelen-en-beveiligen_zorg-op-maat" element={<PageRenderer file="behandelen-en-beveiligen_zorg-op-maat_behandelen-en-beveiligen_zorg-op-maat.json" />} />
                    <Route path="/forensische-psychiatrie/forensisch-psychiatrisch-centrum/fpc-blok6" element={<PageRenderer file="forensische-psychiatrie_forensisch-psychiatrisch-centrum_fpc-blok6.json" />} />
                    <Route path="/forensische-psychiatrie/link-img-2" element={<PageRenderer file="forensische-psychiatrie_link-img-2.json" />} />
                    <Route path="/forensische-psychiatrie/fpc-blok5" element={<PageRenderer file="forensische-psychiatrie_fpc-blok5.json" />} />
                    <Route path="/behandelcentra/hoog-beveiligde-centra_aangemeld_wat-nu" element={<PageRenderer file="behandelcentra_hoog-beveiligde-centra_aangemeld_wat-nu.json" />} />
                    <Route path="/jobs/_jobs_aandeslag" element={<PageRenderer file="jobs__jobs_aandeslag.json" />} />
                    <Route path="/re-integratie/startup-stock-photos" element={<PageRenderer file="re-integratie_startup-stock-photos.json" />} />
                    <Route path="/jobs/_jobs_solliciatie" element={<PageRenderer file="jobs__jobs_solliciatie.json" />} />
                    <Route path="/jobs/_jobs_getuigenis" element={<PageRenderer file="jobs__jobs_getuigenis.json" />} />
                    <Route path="/jobs/_jobs_kiezenvoorfpc" element={<PageRenderer file="jobs__jobs_kiezenvoorfpc.json" />} />
                    <Route path="/over-ons/nieuwsmodule_warm-lopen-voor-het-goede-doel" element={<PageRenderer file="over-ons_nieuwsmodule_warm-lopen-voor-het-goede-doel.json" />} />
                    <Route path="/jobs/fpc-blok8" element={<PageRenderer file="jobs_fpc-blok8.json" />} />
                    <Route path="/jobs/_jobs_solliciteren" element={<PageRenderer file="jobs__jobs_solliciteren.json" />} />
                    <Route path="/over-ons/_over-ons_aandeelhouders" element={<PageRenderer file="over-ons__over-ons_aandeelhouders.json" />} />
                    <Route path="/over-ons/_publicaties-cropped" element={<PageRenderer file="over-ons__publicaties-cropped.json" />} />
                    <Route path="/behandelcentra/fpc-gent-cropped" element={<PageRenderer file="behandelcentra_fpc-gent-cropped.json" />} />
                    <Route path="/behandelcentra/fpc-antwerpen-cropped" element={<PageRenderer file="behandelcentra_fpc-antwerpen-cropped.json" />} />
                    <Route path="/over-ons/_fpc-antwerpen-cropped" element={<PageRenderer file="over-ons__fpc-antwerpen-cropped.json" />} />
                    <Route path="/over-ons/_fpc-gent_inkom-cropped" element={<PageRenderer file="over-ons__fpc-gent_inkom-cropped.json" />} />
                    <Route path="/forensische-psychiatrie/internering/forensische-psychiatrie_internering" element={<PageRenderer file="forensische-psychiatrie_internering_forensische-psychiatrie_internering.json" />} />
                    <Route path="/behandelen-en-beveiligen/_behandeltrajcet-cropped" element={<PageRenderer file="behandelen-en-beveiligen__behandeltrajcet-cropped.json" />} />
                    <Route path="/behandelen-en-beveiligen/_behandeling-cropped" element={<PageRenderer file="behandelen-en-beveiligen__behandeling-cropped.json" />} />
                    <Route path="/re-integratie/_integratie_doorstroom-cropped" element={<PageRenderer file="re-integratie__integratie_doorstroom-cropped.json" />} />
                    <Route path="/re-integratie/_integratie_ketenpartner-cropped" element={<PageRenderer file="re-integratie__integratie_ketenpartner-cropped.json" />} />
                    <Route path="/re-integratie/_integratie_kennisdelen-cropped" element={<PageRenderer file="re-integratie__integratie_kennisdelen-cropped.json" />} />
                    <Route path="/behandelcentra/fpc-antwerpen/fpca_buitenruimte-met-sportmogelijkheden" element={<PageRenderer file="behandelcentra_fpc-antwerpen_fpca_buitenruimte-met-sportmogelijkheden.json" />} />
                    <Route path="/jobs/_jobs_stages" element={<PageRenderer file="jobs__jobs_stages.json" />} />
                    <Route path="/nieuws-en-informatie/_pers-cropped" element={<PageRenderer file="nieuws-en-informatie__pers-cropped.json" />} />
                    <Route path="/jobs/collegas-getuigen/collegas-getuigen-3" element={<PageRenderer file="jobs_collegas-getuigen_collegas-getuigen-3.json" />} />
                    <Route path="/jobs/collegas-getuigen/collegas-getuigen-4" element={<PageRenderer file="jobs_collegas-getuigen_collegas-getuigen-4.json" />} />
                    <Route path="/behandelen-en-beveiligen/behandelingsconcept/behandelen-en-beveiligen_behandelingsconcept" element={<PageRenderer file="behandelen-en-beveiligen_behandelingsconcept_behandelen-en-beveiligen_behandelingsconcept.json" />} />
                    <Route path="/behandelen-en-beveiligen/behandelen-en-beveiligen_behandelingstraject" element={<PageRenderer file="behandelen-en-beveiligen_behandelen-en-beveiligen_behandelingstraject.json" />} />
                    <Route path="/jobs/startup-stock-photos-2" element={<PageRenderer file="jobs_startup-stock-photos-2.json" />} />
                    <Route path="/jobs/jobs_waarom-kiezen-voor" element={<PageRenderer file="jobs_jobs_waarom-kiezen-voor.json" />} />
                    <Route path="/nieuws-en-informatie/nieuws-2" element={<PageRenderer file="nieuws-en-informatie_nieuws-2.json" />} />
                    <Route path="/over-ons/aandeelhouders-met-expertise/over-ons_aandeelhouders-met-expertise" element={<PageRenderer file="over-ons_aandeelhouders-met-expertise_over-ons_aandeelhouders-met-expertise.json" />} />
                    <Route path="/over-ons/ombudsdienst/over-ons_ombudsdienst" element={<PageRenderer file="over-ons_ombudsdienst_over-ons_ombudsdienst.json" />} />
                    <Route path="/jobs/aan-de-slag-in/jobs_facilitaire-dienstverlening-en-technisch-onderhoud" element={<PageRenderer file="jobs_aan-de-slag-in_jobs_facilitaire-dienstverlening-en-technisch-onderhoud.json" />} />
                    <Route path="/home/logo-fpc-antwerpen-2" element={<PageRenderer file="home_logo-fpc-antwerpen-2.json" />} />
                    <Route path="/home/fpc-antwerpen-2" element={<PageRenderer file="home_fpc-antwerpen-2.json" />} />
                    <Route path="/home/fpc-antwerpen-square" element={<PageRenderer file="home_fpc-antwerpen-square.json" />} />
                    <Route path="/behandelcentra/fpc-gent/fpc-blok4" element={<PageRenderer file="behandelcentra_fpc-gent_fpc-blok4.json" />} />
                    <Route path="/behandelcentra/_aangemeld-cropped" element={<PageRenderer file="behandelcentra__aangemeld-cropped.json" />} />
                    <Route path="/jobs/collegas-getuigen/collegas-getuigen-header" element={<PageRenderer file="jobs_collegas-getuigen_collegas-getuigen-header.json" />} />
                    <Route path="/behandelcentra/fpc-gent/contact-2" element={<PageRenderer file="behandelcentra_fpc-gent_contact-2.json" />} />
                    <Route path="/home/fpc-antwerpen-logo-liggend" element={<PageRenderer file="home_fpc-antwerpen-logo-liggend.json" />} />
                    <Route path="/home/fpc-gent-logo-liggend" element={<PageRenderer file="home_fpc-gent-logo-liggend.json" />} />
                    <Route path="/over-ons/over-ons_publicaties" element={<PageRenderer file="over-ons_over-ons_publicaties.json" />} />
                    <Route path="/jobs/collegas-getuigen/collegas-getuigen-5" element={<PageRenderer file="jobs_collegas-getuigen_collegas-getuigen-5.json" />} />
                    <Route path="/kwalitatieve-zorg-groene-handen/kwalitatieve-zorg-in-groene-handen" element={<PageRenderer file="kwalitatieve-zorg-groene-handen_kwalitatieve-zorg-in-groene-handen.json" />} />
                    <Route path="/warmlopen-goede-doel-en-re-integratie/warmlopen-voor-het-goede-doel-en-re-integratie" element={<PageRenderer file="warmlopen-goede-doel-en-re-integratie_warmlopen-voor-het-goede-doel-en-re-integratie.json" />} />
                    <Route path="/laagdrempelige-ombudsfunctie-garandeert-mee-kwaliteit-zorg/illustrations-psychiatric-hospital-gent" element={<PageRenderer file="laagdrempelige-ombudsfunctie-garandeert-mee-kwaliteit-zorg_illustrations-psychiatric-hospital-gent.json" />} />
                    <Route path="/ondersteuningsfonds-menswaardig-leven-en-resocialisatie/fpc_barbara-joseph" element={<PageRenderer file="ondersteuningsfonds-menswaardig-leven-en-resocialisatie_fpc_barbara-joseph.json" />} />
                    <Route path="/betere-kansen-op-resocialisatie-zinvolle-dagbesteding/fpc_barbara-joseph-8-van-67-e1481280223271" element={<PageRenderer file="betere-kansen-op-resocialisatie-zinvolle-dagbesteding_fpc_barbara-joseph-8-van-67-e1481280223271.json" />} />
                    <Route path="/zoeken-naar-evenwicht-behandelen-en-beheersen/p1010047-2-e1476343895750" element={<PageRenderer file="zoeken-naar-evenwicht-behandelen-en-beheersen_p1010047-2-e1476343895750.json" />} />
                    <Route path="/gevarieerd-team-optimale-begeleiding-patienten/gevarieerd-team-optimale-begeleiding" element={<PageRenderer file="gevarieerd-team-optimale-begeleiding-patienten_gevarieerd-team-optimale-begeleiding.json" />} />
                    <Route path="/destigmatisering-geinterneerden-mensen-beeld/destigmatisering-van-gei%cc%88nterneerden" element={<PageRenderer file="destigmatisering-geinterneerden-mensen-beeld_destigmatisering-van-gei%cc%88nterneerden.json" />} />
                    <Route path="/somatische-zorg-vergelijkbaar-gezondheidszorg-vrije-samenleving/somatische-zorg-vergelijkbaar-met-gezondheidszorg" element={<PageRenderer file="somatische-zorg-vergelijkbaar-gezondheidszorg-vrije-samenleving_somatische-zorg-vergelijkbaar-met-gezondheidszorg.json" />} />
                    <Route path="/congres-zeer-intensieve-zorg-binnen-forensische-psychiatrie/fpc-gent-gebouw" element={<PageRenderer file="congres-zeer-intensieve-zorg-binnen-forensische-psychiatrie_fpc-gent-gebouw.json" />} />
                    <Route path="/humane-aanpak-respect-ieders-veiligheid/fpc-gent-gebouw-2" element={<PageRenderer file="humane-aanpak-respect-ieders-veiligheid_fpc-gent-gebouw-2.json" />} />
                    <Route path="/preventief-werken-om-incidenten-voorkomen/preventief-werken-voorkomt-incidenten" element={<PageRenderer file="preventief-werken-om-incidenten-voorkomen_preventief-werken-voorkomt-incidenten.json" />} />
                    <Route path="/buiten-naar-binnen-halen-sporten/buiten-naar-binnen-halen-door-te-sporten" element={<PageRenderer file="buiten-naar-binnen-halen-sporten_buiten-naar-binnen-halen-door-te-sporten.json" />} />
                    <Route path="/behandelcentra/fpc-gent/logo-fpc-gent" element={<PageRenderer file="behandelcentra_fpc-gent_logo-fpc-gent.json" />} />
                    <Route path="/behandelcentra/fpc-gent/logo-fpc-gent-klein" element={<PageRenderer file="behandelcentra_fpc-gent_logo-fpc-gent-klein.json" />} />
                    <Route path="/behandelcentra/fpc-antwerpen/fpc-antwerpen-vestiging" element={<PageRenderer file="behandelcentra_fpc-antwerpen_fpc-antwerpen-vestiging.json" />} />
                    <Route path="/behandelcentra/fpc-antwerpen/fpca_inkom" element={<PageRenderer file="behandelcentra_fpc-antwerpen_fpca_inkom.json" />} />
                    <Route path="/behandelen-en-beveiligen/_zorg-op-maat-cropped" element={<PageRenderer file="behandelen-en-beveiligen__zorg-op-maat-cropped.json" />} />
                    <Route path="/jobs/aan-de-slag-in/group-of-people-with-heads-together-teamwork" element={<PageRenderer file="jobs_aan-de-slag-in_group-of-people-with-heads-together-teamwork.json" />} />
                    <Route path="/jobs/collegas-getuigen/20180710-een-getuigenis-docx-2" element={<PageRenderer file="jobs_collegas-getuigen_20180710-een-getuigenis-docx-2.json" />} />
                    <Route path="/jobs/kiezen-voor-fpc-antwerpen-of-fpc-gent/_jobs-cropped" element={<PageRenderer file="jobs_kiezen-voor-fpc-antwerpen-of-fpc-gent__jobs-cropped.json" />} />
                    <Route path="/informatie-patienten-dunne-grens-sociaal-contact-en-zoeken-naar-aandacht/informatie-van-patie%cc%88nten" element={<PageRenderer file="informatie-patienten-dunne-grens-sociaal-contact-en-zoeken-naar-aandacht_informatie-van-patie%cc%88nten.json" />} />
                    <Route path="/over-ons/website-disclaimer-en-cookiebeleid/website-disclaimer-en-cookiebeleid" element={<PageRenderer file="over-ons_website-disclaimer-en-cookiebeleid_website-disclaimer-en-cookiebeleid.json" />} />
                    <Route path="/over-ons/privacybeleid/privacy-policy" element={<PageRenderer file="over-ons_privacybeleid_privacy-policy.json" />} />
                    <Route path="/uitstroomresultaten-kennen-positieve-evolutie/20190226_illustratie_grafiek-uitstroom" element={<PageRenderer file="uitstroomresultaten-kennen-positieve-evolutie_20190226_illustratie_grafiek-uitstroom.json" />} />
                    <Route path="/integrin-duurzaamheid-en-sociale-integratie-gaan-hand-in-hand/inspire-5-integrin-1" element={<PageRenderer file="integrin-duurzaamheid-en-sociale-integratie-gaan-hand-in-hand_inspire-5-integrin-1.json" />} />
                    <Route path="/integrin-duurzaamheid-en-sociale-integratie-gaan-hand-in-hand/inspire-5-integrin-3" element={<PageRenderer file="integrin-duurzaamheid-en-sociale-integratie-gaan-hand-in-hand_inspire-5-integrin-3.json" />} />
                    <Route path="/integrin-duurzaamheid-en-sociale-integratie-gaan-hand-in-hand/inspire-5-integrin-4" element={<PageRenderer file="integrin-duurzaamheid-en-sociale-integratie-gaan-hand-in-hand_inspire-5-integrin-4.json" />} />
                    <Route path="/integrin-duurzaamheid-en-sociale-integratie-gaan-hand-in-hand/inspire-5-integrin-5" element={<PageRenderer file="integrin-duurzaamheid-en-sociale-integratie-gaan-hand-in-hand_inspire-5-integrin-5.json" />} />
                    <Route path="/integrin-duurzaamheid-en-sociale-integratie-gaan-hand-in-hand/logo" element={<PageRenderer file="integrin-duurzaamheid-en-sociale-integratie-gaan-hand-in-hand_logo.json" />} />
                    <Route path="/open-deuren-in-fpc-antwerpen-en-fpc-gent/img_20180318_094052821" element={<PageRenderer file="open-deuren-in-fpc-antwerpen-en-fpc-gent_img_20180318_094052821.json" />} />
                    <Route path="/fpc-antwerpen-en-fpc-gent-nemen-maatregelen-om-de-verspreiding-van-het-coronavirus-af-te-remmen/corona-1" element={<PageRenderer file="fpc-antwerpen-en-fpc-gent-nemen-maatregelen-om-de-verspreiding-van-het-coronavirus-af-te-remmen_corona-1.json" />} />
                    <Route path="/fpc-antwerpen-en-fpc-gent-nemen-maatregelen-om-de-verspreiding-van-het-coronavirus-af-te-remmen/corona-2" element={<PageRenderer file="fpc-antwerpen-en-fpc-gent-nemen-maatregelen-om-de-verspreiding-van-het-coronavirus-af-te-remmen_corona-2.json" />} />
                    <Route path="/fpc-antwerpen-en-fpc-gent-nemen-maatregelen-om-de-verspreiding-van-het-coronavirus-af-te-remmen/covid-19" element={<PageRenderer file="fpc-antwerpen-en-fpc-gent-nemen-maatregelen-om-de-verspreiding-van-het-coronavirus-af-te-remmen_covid-19.json" />} />
                    <Route path="/fpc-antwerpen-en-fpc-gent-nemen-maatregelen-om-de-verspreiding-van-het-coronavirus-af-te-remmen/corona-2-2" element={<PageRenderer file="fpc-antwerpen-en-fpc-gent-nemen-maatregelen-om-de-verspreiding-van-het-coronavirus-af-te-remmen_corona-2-2.json" />} />
                    <Route path="/fpc-antwerpen-en-fpc-gent-nemen-maatregelen-om-de-verspreiding-van-het-coronavirus-af-te-remmen/corona-2-3" element={<PageRenderer file="fpc-antwerpen-en-fpc-gent-nemen-maatregelen-om-de-verspreiding-van-het-coronavirus-af-te-remmen_corona-2-3.json" />} />
                    <Route path="/tevredenheidsonderzoek-familieleden-van-geinterneerden/online-vragenlijst" element={<PageRenderer file="tevredenheidsonderzoek-familieleden-van-geinterneerden_online-vragenlijst.json" />} />
                    <Route path="/jerusalema-dance-challenge-fpc-gent/jerusalemadancechallenge" element={<PageRenderer file="jerusalema-dance-challenge-fpc-gent_jerusalemadancechallenge.json" />} />
                    <Route path="/onderzoek-naar-onze-patientenpopulatie/panopticon" element={<PageRenderer file="onderzoek-naar-onze-patientenpopulatie_panopticon.json" />} />
                    <Route path="/over-ons/privacybeleid/hoe-kan-u-ons-contacteren" element={<PageRenderer file="over-ons_privacybeleid_hoe-kan-u-ons-contacteren.json" />} />
                    <Route path="/jobs/studenten-on-tour/pic2" element={<PageRenderer file="jobs_studenten-on-tour_pic2.json" />} />
                    <Route path="/jobs/studenten-on-tour/pic3" element={<PageRenderer file="jobs_studenten-on-tour_pic3.json" />} />
                    <Route path="/jobs/studenten-on-tour/pic4" element={<PageRenderer file="jobs_studenten-on-tour_pic4.json" />} />
                    <Route path="/jobs/studenten-on-tour/pic1" element={<PageRenderer file="jobs_studenten-on-tour_pic1.json" />} />
                    <Route path="/covid-19-vaccinatiegraad-van-meer-dan-95/20210930_vaccinatiegraad-fpcnv" element={<PageRenderer file="covid-19-vaccinatiegraad-van-meer-dan-95_20210930_vaccinatiegraad-fpcnv.json" />} />
                    <Route path="/dag-van-de-zorg-zondag-15-mei-2022/20220515_dag-van-de-zorg" element={<PageRenderer file="dag-van-de-zorg-zondag-15-mei-2022_20220515_dag-van-de-zorg.json" />} />
                    <Route path="/dag-van-de-zorg-zondag-15-mei-2022/2022_logo-dvdz-met-datum-mei_rood" element={<PageRenderer file="dag-van-de-zorg-zondag-15-mei-2022_2022_logo-dvdz-met-datum-mei_rood.json" />} />
                    <Route path="/dag-van-de-zorg-zondag-15-mei-2022/2022_logo-dvdz-met-datum-mei" element={<PageRenderer file="dag-van-de-zorg-zondag-15-mei-2022_2022_logo-dvdz-met-datum-mei.json" />} />
                    <Route path="/dag-van-de-zorg-zondag-15-mei-2022/campagnebeeld_dvdz_15mei2022" element={<PageRenderer file="dag-van-de-zorg-zondag-15-mei-2022_campagnebeeld_dvdz_15mei2022.json" />} />
                    <Route path="/jobs/kiezen-voor-fpc-antwerpen-of-fpc-gent/deskundig" element={<PageRenderer file="jobs_kiezen-voor-fpc-antwerpen-of-fpc-gent_deskundig.json" />} />
                    <Route path="/jobs/kiezen-voor-fpc-antwerpen-of-fpc-gent/gedreven" element={<PageRenderer file="jobs_kiezen-voor-fpc-antwerpen-of-fpc-gent_gedreven.json" />} />
                    <Route path="/jobs/kiezen-voor-fpc-antwerpen-of-fpc-gent/menswaardig" element={<PageRenderer file="jobs_kiezen-voor-fpc-antwerpen-of-fpc-gent_menswaardig.json" />} />
                    <Route path="/jobs/kiezen-voor-fpc-antwerpen-of-fpc-gent/verbindend" element={<PageRenderer file="jobs_kiezen-voor-fpc-antwerpen-of-fpc-gent_verbindend.json" />} />
                    <Route path="/officiele-erkenning-voor-kwaliteitsbeleid-binnen-de-zorg/audit-rapport" element={<PageRenderer file="officiele-erkenning-voor-kwaliteitsbeleid-binnen-de-zorg_audit-rapport.json" />} />
                    <Route path="/officiele-erkenning-voor-kwaliteitsbeleid-binnen-de-zorg/nen-en-15224-cmyk" element={<PageRenderer file="officiele-erkenning-voor-kwaliteitsbeleid-binnen-de-zorg_nen-en-15224-cmyk.json" />} />
                    <Route path="/officiele-erkenning-voor-kwaliteitsbeleid-binnen-de-zorg/nen-en-15224-cmyk-2" element={<PageRenderer file="officiele-erkenning-voor-kwaliteitsbeleid-binnen-de-zorg_nen-en-15224-cmyk-2.json" />} />
                    <Route path="/over-ons/klokkenluiderskanaal/whistleblower_qr-code" element={<PageRenderer file="over-ons_klokkenluiderskanaal_whistleblower_qr-code.json" />} />
                    <Route path="/over-ons/klokkenluiderskanaal/klokkenluider" element={<PageRenderer file="over-ons_klokkenluiderskanaal_klokkenluider.json" />} />
                    <Route path="/over-ons/klokkenluiderskanaal/20230322_klokkenluidersbeleid" element={<PageRenderer file="over-ons_klokkenluiderskanaal_20230322_klokkenluidersbeleid.json" />} />
                    <Route path="/over-ons/veilig-versturen-van-privacygevoelige-informatie/fpc-antwerpen_pagina1" element={<PageRenderer file="over-ons_veilig-versturen-van-privacygevoelige-informatie_fpc-antwerpen_pagina1.json" />} />
                    <Route path="/over-ons/veilig-versturen-van-privacygevoelige-informatie/fpc-gent_pagina1" element={<PageRenderer file="over-ons_veilig-versturen-van-privacygevoelige-informatie_fpc-gent_pagina1.json" />} />
                    <Route path="/over-ons/veilig-versturen-van-privacygevoelige-informatie/veilig-mailen" element={<PageRenderer file="over-ons_veilig-versturen-van-privacygevoelige-informatie_veilig-mailen.json" />} />
                    <Route path="/inspectiebezoek-fpc-antwerpen-en-fpc-gent-een-positief-rapport-met-groeikansen-voor-organisatie-en-sector/audit" element={<PageRenderer file="inspectiebezoek-fpc-antwerpen-en-fpc-gent-een-positief-rapport-met-groeikansen-voor-organisatie-en-sector_audit.json" />} />
                    <Route path="/inspectiebezoek-fpc-antwerpen-en-fpc-gent-een-positief-rapport-met-groeikansen-voor-organisatie-en-sector/conclusie-inspectieverslag-5" element={<PageRenderer file="inspectiebezoek-fpc-antwerpen-en-fpc-gent-een-positief-rapport-met-groeikansen-voor-organisatie-en-sector_conclusie-inspectieverslag-5.json" />} />
                    <Route path="/inspectiebezoek-fpc-antwerpen-en-fpc-gent-een-positief-rapport-met-groeikansen-voor-organisatie-en-sector/conclusie-inspectieverslag-1" element={<PageRenderer file="inspectiebezoek-fpc-antwerpen-en-fpc-gent-een-positief-rapport-met-groeikansen-voor-organisatie-en-sector_conclusie-inspectieverslag-1.json" />} />
                    <Route path="/inspectiebezoek-fpc-antwerpen-en-fpc-gent-een-positief-rapport-met-groeikansen-voor-organisatie-en-sector/conclusie-inspectieverslag-2" element={<PageRenderer file="inspectiebezoek-fpc-antwerpen-en-fpc-gent-een-positief-rapport-met-groeikansen-voor-organisatie-en-sector_conclusie-inspectieverslag-2.json" />} />
                    <Route path="/inspectiebezoek-fpc-antwerpen-en-fpc-gent-een-positief-rapport-met-groeikansen-voor-organisatie-en-sector/conclusie-inspectieverslag-3" element={<PageRenderer file="inspectiebezoek-fpc-antwerpen-en-fpc-gent-een-positief-rapport-met-groeikansen-voor-organisatie-en-sector_conclusie-inspectieverslag-3.json" />} />
                    <Route path="/inspectiebezoek-fpc-antwerpen-en-fpc-gent-een-positief-rapport-met-groeikansen-voor-organisatie-en-sector/conclusie-inspectieverslag-4" element={<PageRenderer file="inspectiebezoek-fpc-antwerpen-en-fpc-gent-een-positief-rapport-met-groeikansen-voor-organisatie-en-sector_conclusie-inspectieverslag-4.json" />} />
                    <Route path="/inspectiebezoek-fpc-antwerpen-en-fpc-gent-een-positief-rapport-met-groeikansen-voor-organisatie-en-sector/fpca_fpcg-zi-2023-00421-versie-voor-openbaarheid" element={<PageRenderer file="inspectiebezoek-fpc-antwerpen-en-fpc-gent-een-positief-rapport-met-groeikansen-voor-organisatie-en-sector_fpca_fpcg-zi-2023-00421-versie-voor-openbaarheid.json" />} />
                    <Route path="/nieuws-en-informatie/pers/20230707_perstekst_audit-zi" element={<PageRenderer file="nieuws-en-informatie_pers_20230707_perstekst_audit-zi.json" />} />
                    <Route path="/nieuws-en-informatie/pers/20220315_persmoment_persinfo" element={<PageRenderer file="nieuws-en-informatie_pers_20220315_persmoment_persinfo.json" />} />
                    <Route path="/we-zijn-trots-op-wat-we-doen/20230713_reactie-n-a-v-berichtgeving-rapport-zi" element={<PageRenderer file="we-zijn-trots-op-wat-we-doen_20230713_reactie-n-a-v-berichtgeving-rapport-zi.json" />} />
                    <Route path="/ontdek-tijdens-de-open-geestdagen-wat-er-achter-onze-deuren-gebeurt/logo-2" element={<PageRenderer file="ontdek-tijdens-de-open-geestdagen-wat-er-achter-onze-deuren-gebeurt_logo-2.json" />} />
                    <Route path="/ontdek-tijdens-de-open-geestdagen-wat-er-achter-onze-deuren-gebeurt/open-jij-ook-de-deur-van-je-hoofd" element={<PageRenderer file="ontdek-tijdens-de-open-geestdagen-wat-er-achter-onze-deuren-gebeurt_open-jij-ook-de-deur-van-je-hoofd.json" />} />
                    <Route path="/over-ons/veilig-versturen-van-privacygevoelige-informatie/fpc-gent_pagina2" element={<PageRenderer file="over-ons_veilig-versturen-van-privacygevoelige-informatie_fpc-gent_pagina2.json" />} />
                    <Route path="/over-ons/veilig-versturen-van-privacygevoelige-informatie/fpc-antwerpen_pagina2" element={<PageRenderer file="over-ons_veilig-versturen-van-privacygevoelige-informatie_fpc-antwerpen_pagina2.json" />} />
                    <Route path="/wij-dragen-zorg-voor-een-unieke-doelgroep-kom-en-neem-een-unieke-kijk-achter-de-schermen/2019_fpcg_deelname-dvdz-collage" element={<PageRenderer file="wij-dragen-zorg-voor-een-unieke-doelgroep-kom-en-neem-een-unieke-kijk-achter-de-schermen_2019_fpcg_deelname-dvdz-collage.json" />} />
                    <Route path="/wij-dragen-zorg-voor-een-unieke-doelgroep-kom-en-neem-een-unieke-kijk-achter-de-schermen/campagnebeeld_dvdz_2024" element={<PageRenderer file="wij-dragen-zorg-voor-een-unieke-doelgroep-kom-en-neem-een-unieke-kijk-achter-de-schermen_campagnebeeld_dvdz_2024.json" />} />
                    <Route path="/wij-dragen-zorg-voor-een-unieke-doelgroep-kom-en-neem-een-unieke-kijk-achter-de-schermen/2024_post_sm" element={<PageRenderer file="wij-dragen-zorg-voor-een-unieke-doelgroep-kom-en-neem-een-unieke-kijk-achter-de-schermen_2024_post_sm.json" />} />
                    <Route path="/kleine-stapjes-met-een-grote-betekenis/troeven-van-de-zorg" element={<PageRenderer file="kleine-stapjes-met-een-grote-betekenis_troeven-van-de-zorg.json" />} />
                    <Route path="/kleine-stapjes-met-een-grote-betekenis/patient-harkt-bladeren" element={<PageRenderer file="kleine-stapjes-met-een-grote-betekenis_patient-harkt-bladeren.json" />} />
                    <Route path="/stap-voor-stap-richting-richting-maatschappij/fpc-antwerpen-3" element={<PageRenderer file="stap-voor-stap-richting-richting-maatschappij_fpc-antwerpen-3.json" />} />
                    <Route path="/stap-voor-stap-richting-richting-maatschappij/annick-verhasselt-1" element={<PageRenderer file="stap-voor-stap-richting-richting-maatschappij_annick-verhasselt-1.json" />} />
                    <Route path="/personen-met-psychosegevoeligheid-komen-op-adem-in-een-comfort-room/illustrations-psychiatric-hospital-gent-2" element={<PageRenderer file="personen-met-psychosegevoeligheid-komen-op-adem-in-een-comfort-room_illustrations-psychiatric-hospital-gent-2.json" />} />
                    <Route path="/personen-met-psychosegevoeligheid-komen-op-adem-in-een-comfort-room/comfort-room-mercatordok" element={<PageRenderer file="personen-met-psychosegevoeligheid-komen-op-adem-in-een-comfort-room_comfort-room-mercatordok.json" />} />
                    <Route path="/personen-met-psychosegevoeligheid-komen-op-adem-in-een-comfort-room/comfort-room-mercatordok-2" element={<PageRenderer file="personen-met-psychosegevoeligheid-komen-op-adem-in-een-comfort-room_comfort-room-mercatordok-2.json" />} />
                    <Route path="/somatische-pathologie/fpc-antwerpen-4" element={<PageRenderer file="somatische-pathologie_fpc-antwerpen-4.json" />} />
                    <Route path="/somatische-pathologie/somatische-pathologie-fpca_tabel-2" element={<PageRenderer file="somatische-pathologie_somatische-pathologie-fpca_tabel-2.json" />} />
                    <Route path="/somatische-pathologie/somatische-pathologie-fpca_tabel-1" element={<PageRenderer file="somatische-pathologie_somatische-pathologie-fpca_tabel-1.json" />} />
                    <Route path="/somatische-pathologie/onderzoeksresultaten" element={<PageRenderer file="somatische-pathologie_onderzoeksresultaten.json" />} />
                    <Route path="/uitstroom-en-patientenpopulatie/attachment/3" element={<PageRenderer file="uitstroom-en-patientenpopulatie_attachment_3.json" />} />
                    <Route path="/uitstroom-en-patientenpopulatie/attachment/6" element={<PageRenderer file="uitstroom-en-patientenpopulatie_attachment_6.json" />} />
                    <Route path="/uitstroom-en-patientenpopulatie/attachment/7" element={<PageRenderer file="uitstroom-en-patientenpopulatie_attachment_7.json" />} />
                    <Route path="/uitstroom-en-patientenpopulatie/attachment/2" element={<PageRenderer file="uitstroom-en-patientenpopulatie_attachment_2.json" />} />
                    <Route path="/uitstroom-en-patientenpopulatie/attachment/1" element={<PageRenderer file="uitstroom-en-patientenpopulatie_attachment_1.json" />} />
                    <Route path="/uitstroom-en-patientenpopulatie/combi-4-en-5" element={<PageRenderer file="uitstroom-en-patientenpopulatie_combi-4-en-5.json" />} />
                    <Route path="/psychomotorische-therapie-als-onderdeel-van-de-behandeling/artikel-pmt-2" element={<PageRenderer file="psychomotorische-therapie-als-onderdeel-van-de-behandeling_artikel-pmt-2.json" />} />
                    <Route path="/fpc-antwerpen-en-fpc-gent-versturen-van-privacygevoelige-informatie-op-een-veilige-manier/veilig-mailen-2" element={<PageRenderer file="fpc-antwerpen-en-fpc-gent-versturen-van-privacygevoelige-informatie-op-een-veilige-manier_veilig-mailen-2.json" />} />
                    <Route path="/het-belangrijk-is-dat-patienten-zich-niet-enkel-dader-maar-vooral-ook-mens-voelen/20240425_093312" element={<PageRenderer file="het-belangrijk-is-dat-patienten-zich-niet-enkel-dader-maar-vooral-ook-mens-voelen_20240425_093312.json" />} />
                    <Route path="/familiedag-mercatordok-een-ongedwongen-moment-van-samenzijn/afbeelding1" element={<PageRenderer file="familiedag-mercatordok-een-ongedwongen-moment-van-samenzijn_afbeelding1.json" />} />
                    <Route path="/familiedag-mercatordok-een-ongedwongen-moment-van-samenzijn/afbeelding2" element={<PageRenderer file="familiedag-mercatordok-een-ongedwongen-moment-van-samenzijn_afbeelding2.json" />} />
                    <Route path="/familiedag-mercatordok-een-ongedwongen-moment-van-samenzijn/afbeelding3" element={<PageRenderer file="familiedag-mercatordok-een-ongedwongen-moment-van-samenzijn_afbeelding3.json" />} />
                    <Route path="/verborgen-kunstenaars-in-de-spotlight/135-1713879810" element={<PageRenderer file="verborgen-kunstenaars-in-de-spotlight_135-1713879810.json" />} />
                    <Route path="/leren-om-de-de-kansen-op-re-integratie-en-zelfredzaamheid-te-maximaliseren/fpcg-29" element={<PageRenderer file="leren-om-de-de-kansen-op-re-integratie-en-zelfredzaamheid-te-maximaliseren_fpcg-29.json" />} />
                    <Route path="/het-profiel-van-de-patienten-in-fpc-antwerpen-en-fpc-gent/onderzoek-1_tabel-3" element={<PageRenderer file="het-profiel-van-de-patienten-in-fpc-antwerpen-en-fpc-gent_onderzoek-1_tabel-3.json" />} />
                    <Route path="/het-profiel-van-de-patienten-in-fpc-antwerpen-en-fpc-gent/onderzoek-2_grafiek" element={<PageRenderer file="het-profiel-van-de-patienten-in-fpc-antwerpen-en-fpc-gent_onderzoek-2_grafiek.json" />} />
                    <Route path="/congres-gestoord-of-ongestoord-seksualiteit-in-de-residentiele-forensische-zorg/programma" element={<PageRenderer file="congres-gestoord-of-ongestoord-seksualiteit-in-de-residentiele-forensische-zorg_programma.json" />} />
                    <Route path="/congres-gestoord-of-ongestoord-seksualiteit-in-de-residentiele-forensische-zorg/qr_studiedag-seksualiteit_uitnodiging" element={<PageRenderer file="congres-gestoord-of-ongestoord-seksualiteit-in-de-residentiele-forensische-zorg_qr_studiedag-seksualiteit_uitnodiging.json" />} />
                    <Route path="/congres-gestoord-of-ongestoord-seksualiteit-in-de-residentiele-forensische-zorg/iicoon-seksualiteit" element={<PageRenderer file="congres-gestoord-of-ongestoord-seksualiteit-in-de-residentiele-forensische-zorg_iicoon-seksualiteit.json" />} />
                    <Route path="/netwerkdag-internering-voor-hulpverleners-binnen-zorg-en-justitie/netwerkdag-internering" element={<PageRenderer file="netwerkdag-internering-voor-hulpverleners-binnen-zorg-en-justitie_netwerkdag-internering.json" />} />
                    <Route path="/netwerkdag-internering-voor-hulpverleners-binnen-zorg-en-justitie/netwerkdag-internering_programma" element={<PageRenderer file="netwerkdag-internering-voor-hulpverleners-binnen-zorg-en-justitie_netwerkdag-internering_programma.json" />} />
                    <Route path="/netwerkdag-internering-voor-hulpverleners-binnen-zorg-en-justitie/20241128_netwerkdag-internering-hof-van-beroep-antwerpen-2" element={<PageRenderer file="netwerkdag-internering-voor-hulpverleners-binnen-zorg-en-justitie_20241128_netwerkdag-internering-hof-van-beroep-antwerpen-2.json" />} />
                    <Route path="/ontvluchtingen-en-onttrekkingen-van-patienten-uit-de-vlaamse-forensisch-psychiatrische-centra/absconding_tabel-1" element={<PageRenderer file="ontvluchtingen-en-onttrekkingen-van-patienten-uit-de-vlaamse-forensisch-psychiatrische-centra_absconding_tabel-1.json" />} />
                    <Route path="/ontvluchtingen-en-onttrekkingen-van-patienten-uit-de-vlaamse-forensisch-psychiatrische-centra/conclusie-2" element={<PageRenderer file="ontvluchtingen-en-onttrekkingen-van-patienten-uit-de-vlaamse-forensisch-psychiatrische-centra_conclusie-2.json" />} />
                    <Route path="/fpc-antwerpen-werkt-samen-met-de-buurtgemeenten-aan-het-milieu/bijenhotel_afbeelding2" element={<PageRenderer file="fpc-antwerpen-werkt-samen-met-de-buurtgemeenten-aan-het-milieu_bijenhotel_afbeelding2.json" />} />
                    <Route path="/fpc-antwerpen-werkt-samen-met-de-buurtgemeenten-aan-het-milieu/fpca_samenwerking-buurt_collage" element={<PageRenderer file="fpc-antwerpen-werkt-samen-met-de-buurtgemeenten-aan-het-milieu_fpca_samenwerking-buurt_collage.json" />} />
                    <Route path="/droomuitstappen-geluk-brengen-maakt-gelukkig/blauwe-lucht-met-zon" element={<PageRenderer file="droomuitstappen-geluk-brengen-maakt-gelukkig_blauwe-lucht-met-zon.json" />} />
                    <Route path="/droomuitstappen-geluk-brengen-maakt-gelukkig/jongeman" element={<PageRenderer file="droomuitstappen-geluk-brengen-maakt-gelukkig_jongeman.json" />} />
                    <Route path="/droomuitstappen-geluk-brengen-maakt-gelukkig/droomuv_zwemmen" element={<PageRenderer file="droomuitstappen-geluk-brengen-maakt-gelukkig_droomuv_zwemmen.json" />} />
                    <Route path="/droomuitstappen-geluk-brengen-maakt-gelukkig/droomuv_voetbal" element={<PageRenderer file="droomuitstappen-geluk-brengen-maakt-gelukkig_droomuv_voetbal.json" />} />
                    <Route path="/droomuitstappen-geluk-brengen-maakt-gelukkig/droomuv_daf" element={<PageRenderer file="droomuitstappen-geluk-brengen-maakt-gelukkig_droomuv_daf.json" />} />
                    <Route path="/droomuitstappen-geluk-brengen-maakt-gelukkig/droomuv_mercatordok_collage" element={<PageRenderer file="droomuitstappen-geluk-brengen-maakt-gelukkig_droomuv_mercatordok_collage.json" />} />
                    <Route path="/mens-sana-in-corpore-sano/fpc-antwerpen-5" element={<PageRenderer file="mens-sana-in-corpore-sano_fpc-antwerpen-5.json" />} />
                    <Route path="/een-behandelplan-op-maat-van-de-patient-innovatie-in-zorg/bp_frustratiebarometer_zin-in_daginvulling" element={<PageRenderer file="een-behandelplan-op-maat-van-de-patient-innovatie-in-zorg_bp_frustratiebarometer_zin-in_daginvulling.json" />} />
                    <Route path="/een-behandelplan-op-maat-van-de-patient-innovatie-in-zorg/bp_overzicht-voorbije-periode" element={<PageRenderer file="een-behandelplan-op-maat-van-de-patient-innovatie-in-zorg_bp_overzicht-voorbije-periode.json" />} />
                    <Route path="/een-behandelplan-op-maat-van-de-patient-innovatie-in-zorg/man-sitting-in-the-psychologists-office-and-talking-about-probl" element={<PageRenderer file="een-behandelplan-op-maat-van-de-patient-innovatie-in-zorg_man-sitting-in-the-psychologists-office-and-talking-about-probl.json" />} />
                    <Route path="/mvc-team-spirit-een-uniek-project/fpc-antwerpen-6" element={<PageRenderer file="mvc-team-spirit-een-uniek-project_fpc-antwerpen-6.json" />} />
                    <Route path="/mvc-team-spirit-een-uniek-project/mvc-team-spirit-logo" element={<PageRenderer file="mvc-team-spirit-een-uniek-project_mvc-team-spirit-logo.json" />} />
                    <Route path="/drama-veelzijdige-ervaringsgerichte-therapie/_mg_9219" element={<PageRenderer file="drama-veelzijdige-ervaringsgerichte-therapie__mg_9219.json" />} />
                    <Route path="/kunst-dat-is-twee-keer-kijken/collage-artikel-kunst" element={<PageRenderer file="kunst-dat-is-twee-keer-kijken_collage-artikel-kunst.json" />} />
                    <Route path="/kunst-dat-is-twee-keer-kijken/collage_herbekeken" element={<PageRenderer file="kunst-dat-is-twee-keer-kijken_collage_herbekeken.json" />} />
                    <Route path="/kunst-dat-is-twee-keer-kijken/beeld-senses" element={<PageRenderer file="kunst-dat-is-twee-keer-kijken_beeld-senses.json" />} />
                    <Route path="/samen-op-weg-de-betrokkenheid-van-familie-en-naasten-bij-het-traject-van-patienten/affiche_bijgeknipt" element={<PageRenderer file="samen-op-weg-de-betrokkenheid-van-familie-en-naasten-bij-het-traject-van-patienten_affiche_bijgeknipt.json" />} />
                    <Route path="/een-dag-van-trots/banner-dag-van-de-zorg" element={<PageRenderer file="een-dag-van-trots_banner-dag-van-de-zorg.json" />} />
                    <Route path="/een-dag-van-trots/dvdz_logo_rgb" element={<PageRenderer file="een-dag-van-trots_dvdz_logo_rgb.json" />} />
                    <Route path="/een-dag-van-trots/2025-opendeur-datum-zonder-www" element={<PageRenderer file="een-dag-van-trots_2025-opendeur-datum-zonder-www.json" />} />
                    <Route path="/een-nieuwe-beleving-de-autismebelevingscircuits-box-van-autisme-centraal/samenwerking-magis3-autisme-centraal" element={<PageRenderer file="een-nieuwe-beleving-de-autismebelevingscircuits-box-van-autisme-centraal_samenwerking-magis3-autisme-centraal.json" />} />
                    <Route path="/een-nieuwe-beleving-de-autismebelevingscircuits-box-van-autisme-centraal/een-houten-handigheid" element={<PageRenderer file="een-nieuwe-beleving-de-autismebelevingscircuits-box-van-autisme-centraal_een-houten-handigheid.json" />} />
                    <Route path="/een-nieuwe-beleving-de-autismebelevingscircuits-box-van-autisme-centraal/praktische-indeling" element={<PageRenderer file="een-nieuwe-beleving-de-autismebelevingscircuits-box-van-autisme-centraal_praktische-indeling.json" />} />
                    <Route path="/een-nieuwe-beleving-de-autismebelevingscircuits-box-van-autisme-centraal/duurzame-opdrachtzakken" element={<PageRenderer file="een-nieuwe-beleving-de-autismebelevingscircuits-box-van-autisme-centraal_duurzame-opdrachtzakken.json" />} />
                    <Route path="/een-nieuwe-beleving-de-autismebelevingscircuits-box-van-autisme-centraal/een-houten-handigheid-2" element={<PageRenderer file="een-nieuwe-beleving-de-autismebelevingscircuits-box-van-autisme-centraal_een-houten-handigheid-2.json" />} />
                    <Route path="/een-brug-tussen-binnen-en-buiten-twee-werelden-vinden-elkaar-tijdens-de-eerste-editie-van-parle-fpc/fatih-de-vos-2-720x480" element={<PageRenderer file="een-brug-tussen-binnen-en-buiten-twee-werelden-vinden-elkaar-tijdens-de-eerste-editie-van-parle-fpc_fatih-de-vos-2-720x480.json" />} />
                    <Route path="/een-brug-tussen-binnen-en-buiten-twee-werelden-vinden-elkaar-tijdens-de-eerste-editie-van-parle-fpc/fatih-de-vos-1-1400x480" element={<PageRenderer file="een-brug-tussen-binnen-en-buiten-twee-werelden-vinden-elkaar-tijdens-de-eerste-editie-van-parle-fpc_fatih-de-vos-1-1400x480.json" />} />
                    <Route path="/een-brug-tussen-binnen-en-buiten-twee-werelden-vinden-elkaar-tijdens-de-eerste-editie-van-parle-fpc/de-ouders-van-fatih" element={<PageRenderer file="een-brug-tussen-binnen-en-buiten-twee-werelden-vinden-elkaar-tijdens-de-eerste-editie-van-parle-fpc_de-ouders-van-fatih.json" />} />
                    <Route path="/een-brug-tussen-binnen-en-buiten-twee-werelden-vinden-elkaar-tijdens-de-eerste-editie-van-parle-fpc/avansa" element={<PageRenderer file="een-brug-tussen-binnen-en-buiten-twee-werelden-vinden-elkaar-tijdens-de-eerste-editie-van-parle-fpc_avansa.json" />} />
                    <Route path="/zorg-ook-voor-de-ziel-over-spiritualiteit-en-pastoraat-in-de-forensische-psychiatrie/cirkels-van-smit" element={<PageRenderer file="zorg-ook-voor-de-ziel-over-spiritualiteit-en-pastoraat-in-de-forensische-psychiatrie_cirkels-van-smit.json" />} />
                    <Route path="/van-stilte-naar-samenspel-muziektherapie-in-de-forensische-psychiatrie/fpcg-16" element={<PageRenderer file="van-stilte-naar-samenspel-muziektherapie-in-de-forensische-psychiatrie_fpcg-16.json" />} />
                    <Route path="/van-stilte-naar-samenspel-muziektherapie-in-de-forensische-psychiatrie/fcp-gent" element={<PageRenderer file="van-stilte-naar-samenspel-muziektherapie-in-de-forensische-psychiatrie_fcp-gent.json" />} />
                    <Route path="/waar-zorg-en-complexiteit-samenkomen-de-zeer-intensieve-zorgafdeling-als-baken-voor-patienten-met-specifieke-zorgnoden/complexiteit-van-de-zorg_een-wirwar-van-draden" element={<PageRenderer file="waar-zorg-en-complexiteit-samenkomen-de-zeer-intensieve-zorgafdeling-als-baken-voor-patienten-met-specifieke-zorgnoden_complexiteit-van-de-zorg_een-wirwar-van-draden.json" />} />
                    <Route path="/de-kracht-van-schematherapie-in-persoonlijke-transformatie/afbeelding-bij-fictieve-casus" element={<PageRenderer file="de-kracht-van-schematherapie-in-persoonlijke-transformatie_afbeelding-bij-fictieve-casus.json" />} />
                    <Route path="/de-kracht-van-schematherapie-in-persoonlijke-transformatie/afbeelding-bij-limited-reparenting" element={<PageRenderer file="de-kracht-van-schematherapie-in-persoonlijke-transformatie_afbeelding-bij-limited-reparenting.json" />} />
                    <Route path="/de-kracht-van-schematherapie-in-persoonlijke-transformatie/afbeelding-bij-vaktherapie" element={<PageRenderer file="de-kracht-van-schematherapie-in-persoonlijke-transformatie_afbeelding-bij-vaktherapie.json" />} />
                    <Route path="/de-kracht-van-schematherapie-in-persoonlijke-transformatie/afbeelding-schemas-versus-modi" element={<PageRenderer file="de-kracht-van-schematherapie-in-persoonlijke-transformatie_afbeelding-schemas-versus-modi.json" />} />
                    <Route path="/de-kracht-van-schematherapie-in-persoonlijke-transformatie/afbeelding-bij-meerstoelentechniek" element={<PageRenderer file="de-kracht-van-schematherapie-in-persoonlijke-transformatie_afbeelding-bij-meerstoelentechniek.json" />} />
                    <Route path="/de-kracht-van-schematherapie-in-persoonlijke-transformatie/afbeelding-bij-meerstoelen-1" element={<PageRenderer file="de-kracht-van-schematherapie-in-persoonlijke-transformatie_afbeelding-bij-meerstoelen-1.json" />} />
                    <Route path="/waar-geen-dag-hetzelfde-is-maar-elke-dag-telt/inno" element={<PageRenderer file="waar-geen-dag-hetzelfde-is-maar-elke-dag-telt_inno.json" />} />
                    <Route path="/onderwijs-als-hefboom-tot-herstel-centrum-voor-volwassenonderwijs-kisp-versterkt-kansen-van-patienten/fpcg-29-2" element={<PageRenderer file="onderwijs-als-hefboom-tot-herstel-centrum-voor-volwassenonderwijs-kisp-versterkt-kansen-van-patienten_fpcg-29-2.json" />} />
                    <Route path="/kunst-buiten-de-muren/20250610_152751" element={<PageRenderer file="kunst-buiten-de-muren_20250610_152751.json" />} />
                    <Route path="/kunst-buiten-de-muren/kunstgalerij-apart_collage" element={<PageRenderer file="kunst-buiten-de-muren_kunstgalerij-apart_collage.json" />} />
                    <Route path="/kunst-buiten-de-muren/20250610_160528" element={<PageRenderer file="kunst-buiten-de-muren_20250610_160528.json" />} />
                    <Route path="/fysieke-gezondheid-van-patienten/fpc-fysieke-gezondheid_infographic" element={<PageRenderer file="fysieke-gezondheid-van-patienten_fpc-fysieke-gezondheid_infographic.json" />} />
                    <Route path="/fysieke-gezondheid-van-patienten/fpc-fysieke-gezondheid_thumb" element={<PageRenderer file="fysieke-gezondheid-van-patienten_fpc-fysieke-gezondheid_thumb.json" />} />
                    <Route path="/droomuitstappen-geluk-brengen-maakt-gelukkig/droomuitstap-voetbal" element={<PageRenderer file="droomuitstappen-geluk-brengen-maakt-gelukkig_droomuitstap-voetbal.json" />} />
                    <Route path="/expertisecentrum/expertisecentrum-2" element={<PageRenderer file="expertisecentrum_expertisecentrum-2.json" />} />
                    <Route path="/expertisecentrum/onderzoek" element={<PageRenderer file="expertisecentrum_onderzoek.json" />} />
                    <Route path="/expertisecentrum/opleidingen-2" element={<PageRenderer file="expertisecentrum_opleidingen-2.json" />} />
                    <Route path="/het-welzijn-van-onze-werknemers-is-ook-onze-zorg/mentaal-welzijn" element={<PageRenderer file="het-welzijn-van-onze-werknemers-is-ook-onze-zorg_mentaal-welzijn.json" />} />
                    <Route path="/het-welzijn-van-onze-werknemers-is-ook-onze-zorg/mentaal-welzijn-2" element={<PageRenderer file="het-welzijn-van-onze-werknemers-is-ook-onze-zorg_mentaal-welzijn-2.json" />} />
                    <Route path="/tussen-voorwaarden-en-vrijheid/9c7da70d-b759-4efe-8981-47e863524456" element={<PageRenderer file="tussen-voorwaarden-en-vrijheid_9c7da70d-b759-4efe-8981-47e863524456.json" />} />
                    <Route path="/tussen-voorwaarden-en-vrijheid/affiche-rvs-2025-update-06-20-1082x1536" element={<PageRenderer file="tussen-voorwaarden-en-vrijheid_affiche-rvs-2025-update-06-20-1082x1536.json" />} />
                    <Route path="/tussen-voorwaarden-en-vrijheid/d378086c-5e80-40cc-964b-4ccc2e3c8a27" element={<PageRenderer file="tussen-voorwaarden-en-vrijheid_d378086c-5e80-40cc-964b-4ccc2e3c8a27.json" />} />
                    <Route path="/tussen-voorwaarden-en-vrijheid/7c71a243-371c-423a-94ee-39c03d6efe2a" element={<PageRenderer file="tussen-voorwaarden-en-vrijheid_7c71a243-371c-423a-94ee-39c03d6efe2a.json" />} />
                    <Route path="/expertisecentrum/opleidingen/learning" element={<PageRenderer file="expertisecentrum_opleidingen_learning.json" />} />
                    <Route path="/somatische-pathologie-bij-high-security-geinterneerden/somatische-pathologie_infographic" element={<PageRenderer file="somatische-pathologie-bij-high-security-geinterneerden_somatische-pathologie_infographic.json" />} />
                    <Route path="/somatische-pathologie-bij-high-security-geinterneerden/onderzoek-profiel-high-security-geinterneerden-in-fpc-antwerpen-en-fpc-gent_infographic" element={<PageRenderer file="somatische-pathologie-bij-high-security-geinterneerden_onderzoek-profiel-high-security-geinterneerden-in-fpc-antwerpen-en-fpc-gent_infographic.json" />} />
                    <Route path="/somatische-pathologie-bij-high-security-geinterneerden/evolutie-van-het-risico-op-herval-in-geweldsdelicten_infographic" element={<PageRenderer file="somatische-pathologie-bij-high-security-geinterneerden_evolutie-van-het-risico-op-herval-in-geweldsdelicten_infographic.json" />} />
                    <Route path="/somatische-pathologie-bij-high-security-geinterneerden/hospital-break_infographic" element={<PageRenderer file="somatische-pathologie-bij-high-security-geinterneerden_hospital-break_infographic.json" />} />
                    <Route path="/somatische-pathologie-bij-high-security-geinterneerden/patientenprofielen_infographic" element={<PageRenderer file="somatische-pathologie-bij-high-security-geinterneerden_patientenprofielen_infographic.json" />} />
                    <Route path="/somatische-pathologie-bij-high-security-geinterneerden/somatische-pathologie_infographic-2" element={<PageRenderer file="somatische-pathologie-bij-high-security-geinterneerden_somatische-pathologie_infographic-2.json" />} />
                    <Route path="/zelfregulatie/infographic_zelfregulatie" element={<PageRenderer file="zelfregulatie_infographic_zelfregulatie.json" />} />
                    <Route path="/welzijn-tijdens-covid-19/infographic_onderzoek-netwerk-analyse-corona" element={<PageRenderer file="welzijn-tijdens-covid-19_infographic_onderzoek-netwerk-analyse-corona.json" />} />
                    <Route path="/welzijn-tijdens-covid-19/infographic_covid-19" element={<PageRenderer file="welzijn-tijdens-covid-19_infographic_covid-19.json" />} />
                    <Route path="/zelfregulatie/zelfregulatie_infographic_thumbnail" element={<PageRenderer file="zelfregulatie_zelfregulatie_infographic_thumbnail.json" />} />
                    <Route path="/uitmuntendheid-in-forensische-psychiatrie-internationaal-onderzoek-naar-kwaliteiten-en-correlaties/bjpsych-open" element={<PageRenderer file="uitmuntendheid-in-forensische-psychiatrie-internationaal-onderzoek-naar-kwaliteiten-en-correlaties_bjpsych-open.json" />} />
                    <Route path="/de-interne-rechtspositieregeling-in-een-high-security-setting-welke-lessen-kunnen-geleerd-worden-uit-de-nederlandse-situatie/cover_large" element={<PageRenderer file="de-interne-rechtspositieregeling-in-een-high-security-setting-welke-lessen-kunnen-geleerd-worden-uit-de-nederlandse-situatie_cover_large.json" />} />
                    <Route path="/het-gebruik-van-vrijheidsbeperkende-maatregelen-in-een-hoog-beveiligde-setting-in-belgie-prevalentie-en-risicofactoren/x01602527" element={<PageRenderer file="het-gebruik-van-vrijheidsbeperkende-maatregelen-in-een-hoog-beveiligde-setting-in-belgie-prevalentie-en-risicofactoren_x01602527.json" />} />
                    <Route path="/de-verbanden-tussen-identiteit-en-zowel-risico-als-beschermende-factoren-met-betrekking-tot-gewelddadige-recidive-bij-volwassen-forensische-patienten/downloaden" element={<PageRenderer file="de-verbanden-tussen-identiteit-en-zowel-risico-als-beschermende-factoren-met-betrekking-tot-gewelddadige-recidive-bij-volwassen-forensische-patienten_downloaden.json" />} />
                    <Route path="/waar-samen-werken-aan-herstel-samenwerken-wordt/handen-reiken-naar-elkaar" element={<PageRenderer file="waar-samen-werken-aan-herstel-samenwerken-wordt_handen-reiken-naar-elkaar.json" />} />
                    <Route path="/waar-samen-werken-aan-herstel-samenwerken-wordt/uitroepteken" element={<PageRenderer file="waar-samen-werken-aan-herstel-samenwerken-wordt_uitroepteken.json" />} />
                    <Route path="/waar-samen-werken-aan-herstel-samenwerken-wordt/logo-familie-impact" element={<PageRenderer file="waar-samen-werken-aan-herstel-samenwerken-wordt_logo-familie-impact.json" />} />
                    <Route path="/wat-als-therapie-niet-met-woorden-begint-beelden-als-brug-naar-contact/false" element={<PageRenderer file="wat-als-therapie-niet-met-woorden-begint-beelden-als-brug-naar-contact_false.json" />} />
                    <Route path="/wat-als-therapie-niet-met-woorden-begint-beelden-als-brug-naar-contact/true" element={<PageRenderer file="wat-als-therapie-niet-met-woorden-begint-beelden-als-brug-naar-contact_true.json" />} />
                    <Route path="/wat-als-therapie-niet-met-woorden-begint-beelden-als-brug-naar-contact/voorbeeld" element={<PageRenderer file="wat-als-therapie-niet-met-woorden-begint-beelden-als-brug-naar-contact_voorbeeld.json" />} />
                    <Route path="/de-moestuin-van-tolhuis/p1000999" element={<PageRenderer file="de-moestuin-van-tolhuis_p1000999.json" />} />
                    <Route path="/inclusie-en-beweging/fpcg-19" element={<PageRenderer file="inclusie-en-beweging_fpcg-19.json" />} />
                    <Route path="/inclusie-en-beweging/fcp-gent-2" element={<PageRenderer file="inclusie-en-beweging_fcp-gent-2.json" />} />
                    <Route path="/samenwerking-met-aap-vzw-honden-die-zorgen-voor-verbinding-en-geluksmomenten/aap-vzw_collage-voor-artikel" element={<PageRenderer file="samenwerking-met-aap-vzw-honden-die-zorgen-voor-verbinding-en-geluksmomenten_aap-vzw_collage-voor-artikel.json" />} />
                    <Route path="/samenwerking-met-aap-vzw-honden-die-zorgen-voor-verbinding-en-geluksmomenten/aap_hond-3_met-baasje" element={<PageRenderer file="samenwerking-met-aap-vzw-honden-die-zorgen-voor-verbinding-en-geluksmomenten_aap_hond-3_met-baasje.json" />} />
                    <Route path="/samenwerking-met-aap-vzw-honden-die-zorgen-voor-verbinding-en-geluksmomenten/header_foto" element={<PageRenderer file="samenwerking-met-aap-vzw-honden-die-zorgen-voor-verbinding-en-geluksmomenten_header_foto.json" />} />
                    <Route path="/samenwerking-met-aap-vzw-honden-die-zorgen-voor-verbinding-en-geluksmomenten/aap-vzw" element={<PageRenderer file="samenwerking-met-aap-vzw-honden-die-zorgen-voor-verbinding-en-geluksmomenten_aap-vzw.json" />} />
                    <Route path="/samenwerking-met-aap-vzw-honden-die-zorgen-voor-verbinding-en-geluksmomenten/ontwerp-zonder-titel" element={<PageRenderer file="samenwerking-met-aap-vzw-honden-die-zorgen-voor-verbinding-en-geluksmomenten_ontwerp-zonder-titel.json" />} />
                    <Route path="/herbronning-binnen-de-forensisch-psychiatrische-zorg/img_3457" element={<PageRenderer file="herbronning-binnen-de-forensisch-psychiatrische-zorg_img_3457.json" />} />
                    <Route path="/herbronning-binnen-de-forensisch-psychiatrische-zorg/droom-uv" element={<PageRenderer file="herbronning-binnen-de-forensisch-psychiatrische-zorg_droom-uv.json" />} />
                    <Route path="/herbronning-binnen-de-forensisch-psychiatrische-zorg/comfort-room" element={<PageRenderer file="herbronning-binnen-de-forensisch-psychiatrische-zorg_comfort-room.json" />} />
                    <Route path="/evolutie-van-het-risico-op-herval-in-geweldsdelicten-verschillende-trajecten/evolutie-van-het-risico-op-herval-in-geweldsdelicten_verschillende-trajecten_thumbnail" element={<PageRenderer file="evolutie-van-het-risico-op-herval-in-geweldsdelicten-verschillende-trajecten_evolutie-van-het-risico-op-herval-in-geweldsdelicten_verschillende-trajecten_thumbnail.json" />} />
                    <Route path="/evolutie-van-het-risico-op-herval-in-geweldsdelicten-verschillende-trajecten/onderzoek-hkt-r-multi-group_infographic" element={<PageRenderer file="evolutie-van-het-risico-op-herval-in-geweldsdelicten-verschillende-trajecten_onderzoek-hkt-r-multi-group_infographic.json" />} />
                    <Route path="/evolutie-van-het-risico-op-herval-in-geweldsdelicten-bestaan-er-verschillende-trajecten/hkt-r_onderzoeksvraag-1" element={<PageRenderer file="evolutie-van-het-risico-op-herval-in-geweldsdelicten-bestaan-er-verschillende-trajecten_hkt-r_onderzoeksvraag-1.json" />} />
                    <Route path="/jobs/job-landingspagina-sociotherapie/rekrutering_campagnemateriaal_website_omslagfoto" element={<PageRenderer file="jobs_job-landingspagina-sociotherapie_rekrutering_campagnemateriaal_website_omslagfoto.json" />} />
                    <Route path="/jobs/job-landingspagina-sociotherapie/rekrutering_campagnemateriaal_website_simon" element={<PageRenderer file="jobs_job-landingspagina-sociotherapie_rekrutering_campagnemateriaal_website_simon.json" />} />
                    <Route path="/jobs/job-landingspagina-sociotherapie/rekrutering_campagnemateriaal_website_inno" element={<PageRenderer file="jobs_job-landingspagina-sociotherapie_rekrutering_campagnemateriaal_website_inno.json" />} />
                    <Route path="/jobs/job-landingspagina-sociotherapie/rekrutering_campagnemateriaal_website_michel" element={<PageRenderer file="jobs_job-landingspagina-sociotherapie_rekrutering_campagnemateriaal_website_michel.json" />} />
                    <Route path="/jobs/job-landingspagina-sociotherapie/rekrutering_campagnemateriaal_website_tim" element={<PageRenderer file="jobs_job-landingspagina-sociotherapie_rekrutering_campagnemateriaal_website_tim.json" />} />
                    <Route path="/jobs/job-landingspagina-sociotherapie/rekrutering_campagnemateriaal_website_thiago" element={<PageRenderer file="jobs_job-landingspagina-sociotherapie_rekrutering_campagnemateriaal_website_thiago.json" />} />
                    <Route path="/hoofgeneesheer-fpc-gent-in-de-volksjury-achter-de-crime-scene/de-volksjury" element={<PageRenderer file="hoofgeneesheer-fpc-gent-in-de-volksjury-achter-de-crime-scene_de-volksjury.json" />} />
                    <Route path="/jobs/job-landingspagina-therapeutisch-assistent-groepsbegeleider/knop-getuigenissen-ambassadeurs" element={<PageRenderer file="jobs_job-landingspagina-therapeutisch-assistent-groepsbegeleider_knop-getuigenissen-ambassadeurs.json" />} />
                    <Route path="/meer-dan-meubels-hoe-een-huiselijke-leefgroep-voor-meer-contact-en-welzijn-zorgt/20251111_1858222" element={<PageRenderer file="meer-dan-meubels-hoe-een-huiselijke-leefgroep-voor-meer-contact-en-welzijn-zorgt_20251111_1858222.json" />} />
                    <Route path="/meer-dan-meubels-hoe-een-huiselijke-leefgroep-voor-meer-contact-en-welzijn-zorgt/f9b84a35-ca31-4866-b6c2-e4661bed2034" element={<PageRenderer file="meer-dan-meubels-hoe-een-huiselijke-leefgroep-voor-meer-contact-en-welzijn-zorgt_f9b84a35-ca31-4866-b6c2-e4661bed2034.json" />} />
                    <Route path="/meer-dan-meubels-hoe-een-huiselijke-leefgroep-voor-meer-contact-en-welzijn-zorgt/afdeling-mercatordok_project-huiselijkheid_collage-leefgroep" element={<PageRenderer file="meer-dan-meubels-hoe-een-huiselijke-leefgroep-voor-meer-contact-en-welzijn-zorgt_afdeling-mercatordok_project-huiselijkheid_collage-leefgroep.json" />} />
                    <Route path="/meer-dan-meubels-hoe-een-huiselijke-leefgroep-voor-meer-contact-en-welzijn-zorgt/20251111_171145" element={<PageRenderer file="meer-dan-meubels-hoe-een-huiselijke-leefgroep-voor-meer-contact-en-welzijn-zorgt_20251111_171145.json" />} />
                    <Route path="/jobs/job-landingspagina-sociotherapie/foto-website-lysa-1" element={<PageRenderer file="jobs_job-landingspagina-sociotherapie_foto-website-lysa-1.json" />} />
                    <Route path="/jobs/job-landingspagina-woon-en-leefgroepbegeleider/van-cronenburg-lotte" element={<PageRenderer file="jobs_job-landingspagina-woon-en-leefgroepbegeleider_van-cronenburg-lotte.json" />} />
                    <Route path="/jobs/job-landingspagina-sociotherapie/rekrutering_campagnemateriaal_banner-vpk" element={<PageRenderer file="jobs_job-landingspagina-sociotherapie_rekrutering_campagnemateriaal_banner-vpk.json" />} />
                    <Route path="/jobs/job-landingspagina-sociotherapie/banner-ta-1" element={<PageRenderer file="jobs_job-landingspagina-sociotherapie_banner-ta-1.json" />} />
                    <Route path="/jobs/job-landingspagina-sociotherapie/banner-ta-2" element={<PageRenderer file="jobs_job-landingspagina-sociotherapie_banner-ta-2.json" />} />
                    <Route path="/jobs/job-landingspagina-sociotherapie/banner-wlb-1" element={<PageRenderer file="jobs_job-landingspagina-sociotherapie_banner-wlb-1.json" />} />
                    <Route path="/jobs/job-landingspagina-sociotherapie/banner-wlb-2" element={<PageRenderer file="jobs_job-landingspagina-sociotherapie_banner-wlb-2.json" />} />
                    <Route path="/events" element={<PageRenderer file="events.json" />} />
                    <Route path="/events/agressiehantering-de-escalerend-werken-en-fixatieloos-afzonderen-procesbegeleiding-en-implementatie-in-uw-organisatie" element={<PageRenderer file="events_agressiehantering-de-escalerend-werken-en-fixatieloos-afzonderen-procesbegeleiding-en-implementatie-in-uw-organisatie.json" />} />
                    <Route path="/events/agressiehantering-de-escalerend-werken-en-fixatieloos-afzonderen-opleidingspakket-voor-teams" element={<PageRenderer file="events_agressiehantering-de-escalerend-werken-en-fixatieloos-afzonderen-opleidingspakket-voor-teams.json" />} />
                    <Route path="/events/milieutherapeutisch-werken-in-een-forensische-setting-theorie-en-praktijk-2" element={<PageRenderer file="events_milieutherapeutisch-werken-in-een-forensische-setting-theorie-en-praktijk-2.json" />} />
                    <Route path="/events/milieutherapeutisch-werken-in-een-forensische-setting-theorie-en-praktijk" element={<PageRenderer file="events_milieutherapeutisch-werken-in-een-forensische-setting-theorie-en-praktijk.json" />} />
                    <Route path="/events/herstelgericht-werken-in-de-forensische-zorg-2" element={<PageRenderer file="events_herstelgericht-werken-in-de-forensische-zorg-2.json" />} />
                    <Route path="/events/herstelgericht-werken-in-de-forensische-zorg" element={<PageRenderer file="events_herstelgericht-werken-in-de-forensische-zorg.json" />} />
                    <Route path="/events/risicomanagement-op-de-werkvloer-praktische-handvaten-voor-de-forensisch-hulpverlener" element={<PageRenderer file="events_risicomanagement-op-de-werkvloer-praktische-handvaten-voor-de-forensisch-hulpverlener.json" />} />
                    <Route path="/events/risicomanagement-op-de-werkvloer-praktische-handvaten-voor-de-forensisch-hulpverlener-2" element={<PageRenderer file="events_risicomanagement-op-de-werkvloer-praktische-handvaten-voor-de-forensisch-hulpverlener-2.json" />} />
                    <Route path="/events/delicttheorie-de-basis-van-een-forensisch-psychiatrisch-behandelplan" element={<PageRenderer file="events_delicttheorie-de-basis-van-een-forensisch-psychiatrisch-behandelplan.json" />} />
                    <Route path="/category/feiten-en-cijfers" element={<PageRenderer file="category_feiten-en-cijfers.json" />} />
                    <Route path="/category/getuigenissen" element={<PageRenderer file="category_getuigenissen.json" />} />
                    <Route path="/category/kwaliteitsvolle-zorg" element={<PageRenderer file="category_kwaliteitsvolle-zorg.json" />} />
                    <Route path="/category/projecten-en-activiteiten-evenementen" element={<PageRenderer file="category_projecten-en-activiteiten-evenementen.json" />} />
                    <Route path="/category/wetenschappelijk-onderzoek" element={<PageRenderer file="category_wetenschappelijk-onderzoek.json" />} />
                    <Route path="/author/sandra" element={<PageRenderer file="author_sandra.json" />} />
                    <Route path="/author/sjadmin" element={<PageRenderer file="author_sjadmin.json" />} />
                    <Route path="/sitemap" element={<Sitemap />} />
                    <Route path="*" element={<div className="p-20 text-center text-gray-400 font-bold">404 - Pagina niet gevonden</div>} />
                </Routes>
            </main>

            <Footer />
        </div>
    </Router>
  );
}

export default App;